-- ============================================================================
-- Showroom Workspace V2 — manual migration  (SCHEMA FROZEN 2026-10-07)
-- Generated by `prisma migrate diff` (read-only against the live DB).
--
-- THIS DATABASE PREDATES PRISMA MIGRATE. Do not run `prisma migrate deploy`
-- or `prisma db push`. See db/migrations/README.md.
--
-- Additive only: no DROP, TRUNCATE, RENAME, ALTER COLUMN, SET NOT NULL on an
-- existing table, and no DML. Every column added to QuoteLead is nullable, so
-- current rows and the code reading them are unaffected.
--
-- Wrapped in a transaction: PostgreSQL DDL is transactional, so a failure
-- part-way rolls back rather than leaving a half-migrated schema.
-- ============================================================================

BEGIN;

-- CreateEnum
CREATE TYPE "LeadStage" AS ENUM ('NEW', 'CONTACTED', 'QUALIFIED', 'QUOTING', 'QUOTE_SENT', 'FOLLOW_UP', 'WON', 'LOST');

-- CreateEnum
CREATE TYPE "LeadRequestType" AS ENUM ('QUOTATION', 'SHOWROOM_CONSULTATION', 'TECHNICAL_CHECK');

-- CreateEnum
CREATE TYPE "QuoteStatus" AS ENUM ('DRAFT', 'SENT', 'ACCEPTED', 'REJECTED', 'EXPIRED');

-- CreateEnum
CREATE TYPE "LeadActivityType" AS ENUM ('NOTE', 'CALL', 'MESSAGE', 'MEETING', 'QUOTE_SENT', 'FOLLOW_UP', 'TECHNICAL_CHECK', 'STAGE_CHANGE');

-- CreateEnum
CREATE TYPE "LeadNextActionType" AS ENUM ('CALL', 'MESSAGE', 'MEETING', 'SEND_QUOTE', 'FOLLOW_UP', 'TECHNICAL_CHECK');

-- CreateEnum
CREATE TYPE "QuoteLineType" AS ENUM ('PRODUCT', 'SERVICE');

-- CreateEnum
CREATE TYPE "OfferAvailability" AS ENUM ('AVAILABLE', 'MADE_TO_ORDER', 'OUT_OF_STOCK', 'CONTACT_REQUIRED', 'UNKNOWN');

-- AlterTable
ALTER TABLE "QuoteLead" ADD COLUMN     "assignedToId" TEXT,
ADD COLUMN     "contextJson" JSONB,
ADD COLUMN     "firstContactAt" TIMESTAMP(3),
ADD COLUMN     "nextActionAt" TIMESTAMP(3),
ADD COLUMN     "nextActionNote" TEXT,
ADD COLUMN     "nextActionType" "LeadNextActionType",
ADD COLUMN     "requestType" "LeadRequestType",
ADD COLUMN     "stage" "LeadStage";

-- CreateTable
CREATE TABLE "Quote" (
    "id" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "leadId" TEXT,
    "showroomId" TEXT NOT NULL,
    "status" "QuoteStatus" NOT NULL DEFAULT 'DRAFT',
    "customerNameSnapshot" TEXT NOT NULL,
    "customerPhoneSnapshot" TEXT,
    "customerEmailSnapshot" TEXT,
    "subtotal" INTEGER NOT NULL DEFAULT 0,
    "discount" INTEGER NOT NULL DEFAULT 0,
    "total" INTEGER NOT NULL DEFAULT 0,
    "validUntil" TIMESTAMP(3),
    "notes" TEXT,
    "sentAt" TIMESTAMP(3),
    "decidedAt" TIMESTAMP(3),
    "createdById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Quote_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "QuoteLine" (
    "id" TEXT NOT NULL,
    "quoteId" TEXT NOT NULL,
    "type" "QuoteLineType" NOT NULL DEFAULT 'PRODUCT',
    "productId" TEXT,
    "skuSnapshot" TEXT,
    "nameSnapshot" TEXT NOT NULL,
    "brandSnapshot" TEXT,
    "description" TEXT,
    "quantity" INTEGER NOT NULL DEFAULT 1,
    "referencePriceSnapshot" INTEGER,
    "unitPrice" INTEGER NOT NULL,
    "discountAmount" INTEGER NOT NULL DEFAULT 0,
    "lineTotal" INTEGER NOT NULL,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "QuoteLine_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "LeadActivity" (
    "id" TEXT NOT NULL,
    "leadId" TEXT NOT NULL,
    "showroomId" TEXT NOT NULL,
    "type" "LeadActivityType" NOT NULL,
    "body" TEXT,
    "metadataJson" JSONB,
    "isInternal" BOOLEAN NOT NULL DEFAULT true,
    "dueAt" TIMESTAMP(3),
    "doneAt" TIMESTAMP(3),
    "createdById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "LeadActivity_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ShowroomProductOffer" (
    "id" TEXT NOT NULL,
    "showroomId" TEXT NOT NULL,
    "productId" TEXT NOT NULL,
    "isOffered" BOOLEAN NOT NULL DEFAULT true,
    "showroomPrice" INTEGER,
    "promotionPrice" INTEGER,
    "availability" "OfferAvailability" NOT NULL DEFAULT 'UNKNOWN',
    "leadTimeDays" INTEGER,
    "note" TEXT,
    "updatedById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ShowroomProductOffer_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Quote_code_key" ON "Quote"("code");

-- CreateIndex
CREATE INDEX "Quote_showroomId_status_idx" ON "Quote"("showroomId", "status");

-- CreateIndex
CREATE INDEX "Quote_leadId_idx" ON "Quote"("leadId");

-- CreateIndex
CREATE INDEX "QuoteLine_quoteId_idx" ON "QuoteLine"("quoteId");

-- CreateIndex
CREATE INDEX "LeadActivity_leadId_createdAt_idx" ON "LeadActivity"("leadId", "createdAt");

-- CreateIndex
CREATE INDEX "LeadActivity_showroomId_dueAt_idx" ON "LeadActivity"("showroomId", "dueAt");

-- CreateIndex
CREATE INDEX "ShowroomProductOffer_showroomId_isOffered_idx" ON "ShowroomProductOffer"("showroomId", "isOffered");

-- CreateIndex
CREATE UNIQUE INDEX "ShowroomProductOffer_showroomId_productId_key" ON "ShowroomProductOffer"("showroomId", "productId");

-- CreateIndex
CREATE INDEX "QuoteLead_showroomId_stage_idx" ON "QuoteLead"("showroomId", "stage");

-- CreateIndex
CREATE INDEX "QuoteLead_showroomId_nextActionAt_idx" ON "QuoteLead"("showroomId", "nextActionAt");

-- CreateIndex
CREATE INDEX "QuoteLead_showroomId_requestType_idx" ON "QuoteLead"("showroomId", "requestType");

-- AddForeignKey
ALTER TABLE "QuoteLead" ADD CONSTRAINT "QuoteLead_assignedToId_fkey" FOREIGN KEY ("assignedToId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Quote" ADD CONSTRAINT "Quote_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "QuoteLead"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Quote" ADD CONSTRAINT "Quote_showroomId_fkey" FOREIGN KEY ("showroomId") REFERENCES "Showroom"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Quote" ADD CONSTRAINT "Quote_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "QuoteLine" ADD CONSTRAINT "QuoteLine_quoteId_fkey" FOREIGN KEY ("quoteId") REFERENCES "Quote"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "QuoteLine" ADD CONSTRAINT "QuoteLine_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LeadActivity" ADD CONSTRAINT "LeadActivity_leadId_fkey" FOREIGN KEY ("leadId") REFERENCES "QuoteLead"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LeadActivity" ADD CONSTRAINT "LeadActivity_showroomId_fkey" FOREIGN KEY ("showroomId") REFERENCES "Showroom"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LeadActivity" ADD CONSTRAINT "LeadActivity_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ShowroomProductOffer" ADD CONSTRAINT "ShowroomProductOffer_showroomId_fkey" FOREIGN KEY ("showroomId") REFERENCES "Showroom"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ShowroomProductOffer" ADD CONSTRAINT "ShowroomProductOffer_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ShowroomProductOffer" ADD CONSTRAINT "ShowroomProductOffer_updatedById_fkey" FOREIGN KEY ("updatedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;


COMMIT;
