import { Lead } from '@/lib/types';

export const adminDemoAnalytics = {
  weeklyRequests: [
    { name: 'T2', value: 2 },
    { name: 'T3', value: 4 },
    { name: 'T4', value: 3 },
    { name: 'T5', value: 6 },
    { name: 'T6', value: 5 },
    { name: 'T7', value: 8 },
    { name: 'CN', value: 4 },
  ],
  leadStatusDistribution: [
    { name: 'Mới', value: 5 },
    { name: 'Đã liên hệ', value: 8 },
    { name: 'Đã báo giá', value: 4 },
    { name: 'Đã chốt', value: 6 },
    { name: 'Mất lead', value: 1 },
  ],
  budgetDistribution: [
    { name: 'Dưới 20 triệu', value: 4 },
    { name: '20M–40M', value: 9 },
    { name: '40M–60M', value: 7 },
    { name: 'Trên 60 triệu', value: 4 },
  ]
};

export const demoLeadsSeed: Lead[] = [
  {
    id: 'lead-1',
    requestCode: 'REQ-DEMO-01',
    customerName: 'Nguyễn Minh Thùy',
    phone: '0901234567',
    email: 'thuy@example.com',
    roomType: 'Phòng tắm căn hộ nhỏ',
    budgetRange: '30M–60M',
    selectedProducts: [
      {
        productId: 'prod-lavabo-1',
        name: 'Lavabo đặt bàn',
        category: 'Basin',
        brand: 'TOTO',
        sku: 'LT4716',
        priceMin: 2000000,
        priceMax: 2000000,
        priceRange: '2.000.000đ',
        quantity: 1,
        image: '/images/products/lavabo.jpg',
        showroomName: 'Luxbath',
        showroomLocation: 'HCM',
        addedAt: new Date().toISOString()
      }
    ],
    estimatedValueMin: 2000000,
    estimatedValueMax: 5000000,
    status: 'Mới',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    consent: true,
    needsInstallation: true,
  },
  {
    id: 'lead-2',
    requestCode: 'REQ-DEMO-02',
    customerName: 'Anh Hoàng',
    phone: '0912345678',
    roomType: 'Phòng tắm master',
    budgetRange: '60M+',
    selectedProducts: [],
    estimatedValueMin: 60000000,
    estimatedValueMax: 100000000,
    status: 'Đã liên hệ',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    consent: true,
    notes: 'Cần thiết kế thêm tủ lavabo',
  },
  {
    id: 'lead-3',
    requestCode: 'REQ-DEMO-03',
    customerName: 'Chị Linh',
    phone: '0987654321',
    roomType: 'Homestay bathroom combo',
    budgetRange: 'Under 30M',
    selectedProducts: [],
    estimatedValueMin: 20000000,
    estimatedValueMax: 40000000,
    status: 'Đã báo giá',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    consent: true,
  },
  {
    id: 'lead-4',
    requestCode: 'REQ-DEMO-04',
    customerName: 'Gia đình Minh Anh',
    phone: '0909090909',
    roomType: 'Renovation bathroom',
    budgetRange: '30M–60M',
    selectedProducts: [],
    estimatedValueMin: 40000000,
    estimatedValueMax: 70000000,
    status: 'Đã chốt',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    consent: true,
  },
  {
    id: 'lead-5',
    requestCode: 'REQ-DEMO-05',
    customerName: 'Khách showroom Luxbath',
    phone: '0933333333',
    selectedConcept: 'Concept Japandi',
    roomType: 'Phòng tắm',
    budgetRange: '30M–60M',
    selectedProducts: [],
    estimatedValueMin: 30000000,
    estimatedValueMax: 60000000,
    status: 'Mất lead',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    consent: true,
    adminNote: 'Khách chọn nhà thầu khác',
  }
];
