import { Concept, Product, Lead, BlogPost } from './types';
import { generatedConcepts } from './data/concepts';

// ─── PRODUCTS ─────────────────────────────────────────────────────────────────

export const products = [
  {
    id: 'p-001',
    name: 'Lavabo đặt bàn Sora Ceramic',
    category: 'Basin',
    brand: 'INAX',
    sku: 'INX-LVB-001',
    priceMin: 2_500_000,
    priceMax: 3_800_000,
    priceRange: '2.500.000đ – 3.800.000đ',
    material: 'Sứ ceramic',
    finish: 'Trắng bóng',
    size: '55 × 40 cm',
    image: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=600&q=80',
    availability: 'In Stock',
    suitableFor: ['Phòng tắm căn hộ', 'Phong cách tối giản'],
    description: 'Lavabo đặt bàn dáng oval thanh lịch, phù hợp với phòng tắm căn hộ đô thị hiện đại.',
    style: 'Minimal',
    showroomName: 'LivLab Partner – INAX Flagship',
    showroomLocation: 'Mỹ Đình, Hà Nội',
    showroomContact: '024 3793 9999',
    sellerType: 'Showroom đối tác',
  },
  {
    id: 'p-002',
    name: 'Vòi lavabo Tono Chrome',
    category: 'Faucet',
    brand: 'Grohe',
    sku: 'GRO-VLV-002',
    priceMin: 3_200_000,
    priceMax: 4_900_000,
    priceRange: '3.200.000đ – 4.900.000đ',
    material: 'Đồng thau',
    finish: 'Chrome bóng',
    image: 'https://images.unsplash.com/photo-1620626011761-996317702782?w=600&q=80',
    availability: 'In Stock',
    suitableFor: ['Phòng tắm cao cấp', 'Japandi', 'Hotel'],
    description: 'Vòi lavabo 1 lỗ thân trụ gọn, tay gạt đơn dễ điều chỉnh nhiệt độ, chrome bóng lâu bền.',
    style: 'Modern',
    showroomName: 'LivLab Partner – Grohe Studio',
    showroomLocation: 'Hoàng Quốc Việt, Hà Nội',
    showroomContact: '024 3566 8888',
    sellerType: 'Showroom đối tác',
  },
  {
    id: 'p-003',
    name: 'Gương LED Aura Round',
    category: 'Mirror',
    brand: 'Deens',
    sku: 'DNS-GNG-003',
    priceMin: 1_800_000,
    priceMax: 2_800_000,
    priceRange: '1.800.000đ – 2.800.000đ',
    material: 'Kính cường lực',
    finish: 'Viền bạc tự nhiên',
    size: 'Ø 60 cm',
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80',
    availability: 'In Stock',
    suitableFor: ['Phòng tắm', 'Phòng ngủ'],
    description: 'Gương tròn viền LED âm ánh sáng ấm 3000K, chống hơi nước, tạo không gian thư giãn.',
    style: 'Minimal',
    showroomName: 'Deens Lighting & Mirror',
    showroomLocation: 'Kim Mã, Hà Nội',
    showroomContact: '024 6688 5500',
    sellerType: 'Nhà phân phối chính thức',
  },
  {
    id: 'p-004',
    name: 'Sen tắm Rainline Rainfall',
    category: 'Shower',
    brand: 'Hansgrohe',
    sku: 'HAN-STM-004',
    priceMin: 6_500_000,
    priceMax: 9_200_000,
    priceRange: '6.500.000đ – 9.200.000đ',
    material: 'Inox 304',
    finish: 'Chrome bóng',
    size: 'Đầu sen Ø 300 mm',
    image: 'https://images.unsplash.com/photo-1564540586988-aa4e53c3d799?w=600&q=80',
    availability: 'In Stock',
    suitableFor: ['Phòng tắm cao cấp', 'Hotel', 'Ensuite'],
    description: 'Bộ sen tắm mưa đầu tròn 300mm với thanh ray và vòi cầm tay đi kèm.',
    style: 'Hotel',
    showroomName: 'LivLab Partner – Hansgrohe',
    showroomLocation: 'Trần Duy Hưng, Hà Nội',
    showroomContact: '024 3562 1234',
    sellerType: 'Showroom đối tác',
  },
  {
    id: 'p-005',
    name: 'Bồn cầu một khối Nami',
    category: 'Toilet',
    brand: 'TOTO',
    sku: 'TOT-BCT-005',
    priceMin: 5_500_000,
    priceMax: 7_800_000,
    priceRange: '5.500.000đ – 7.800.000đ',
    material: 'Sứ cao cấp',
    finish: 'Trắng bóng',
    size: '68 × 37 × 77 cm',
    image: 'https://images.unsplash.com/photo-1613756788434-61dd05b44d43?w=600&q=80',
    availability: 'In Stock',
    suitableFor: ['Phòng tắm', 'Ensuite'],
    description: 'Bồn cầu một khối thiết kế gọn, nắp êm giảm chấn, xả nước tiết kiệm 6/3L.',
    style: 'Minimal',
    showroomName: 'LivLab Partner – TOTO Showroom',
    showroomLocation: 'Đống Đa, Hà Nội',
    showroomContact: '024 3775 0101',
    sellerType: 'Showroom đối tác',
  },
  {
    id: 'p-006',
    name: 'Gạch ốp Travertine Beige',
    category: 'Tiles',
    brand: 'Granito',
    sku: 'GRN-GAO-006',
    priceMin: 950_000,
    priceMax: 1_400_000,
    priceRange: '950.000đ – 1.400.000đ/m²',
    material: 'Gạch porcelain',
    finish: 'Mờ tự nhiên',
    size: '60 × 120 cm',
    image: 'https://images.unsplash.com/photo-1615971677499-5467cbab01b0?w=600&q=80',
    availability: 'In Stock',
    suitableFor: ['Phòng tắm', 'Phòng khách', 'Bếp'],
    description: 'Gạch lớn cảm giác đá travertine tự nhiên, chống trơn, phù hợp ốp tường và lát sàn.',
    style: 'Japandi',
    showroomName: 'Granito Tile Center',
    showroomLocation: 'Thanh Xuân, Hà Nội',
    showroomContact: '024 3556 7890',
    sellerType: 'Nhà phân phối chính thức',
  },
  {
    id: 'p-007',
    name: 'Tủ lavabo Moku Wood',
    category: 'Cabinet',
    brand: 'Woodline',
    sku: 'WDL-TLV-007',
    priceMin: 7_200_000,
    priceMax: 10_500_000,
    priceRange: '7.200.000đ – 10.500.000đ',
    material: 'Gỗ oak veneer / MDF chống ẩm',
    finish: 'Oak tự nhiên',
    size: '80 × 45 × 55 cm',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80',
    availability: 'Made to Order',
    suitableFor: ['Phòng tắm', 'Japandi', 'Warm Neutral'],
    description: 'Tủ lavabo treo tường cánh đẩy, mặt gỗ oak veneer phủ dầu bảo vệ chống ẩm.',
    style: 'Japandi',
    showroomName: 'Woodline Furniture Studio',
    showroomLocation: 'Cầu Giấy, Hà Nội',
    showroomContact: '024 6688 3300',
    sellerType: 'Xưởng sản xuất nội thất',
  },
  {
    id: 'p-008',
    name: 'Đèn tường Halo Warm',
    category: 'Lighting',
    brand: 'Philips',
    sku: 'PHL-DGL-008',
    priceMin: 1_400_000,
    priceMax: 2_100_000,
    priceRange: '1.400.000đ – 2.100.000đ',
    material: 'Nhôm cao cấp',
    finish: 'Đen mờ',
    size: '30 × 8 cm',
    image: 'https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=600&q=80',
    availability: 'In Stock',
    suitableFor: ['Phòng tắm', 'Phòng ngủ'],
    description: 'Đèn LED thanh dọc âm gương IP44, ánh sáng vàng ấm 2700K, dimmer tích hợp.',
    style: 'Minimal',
    showroomName: 'Philips Lighting Vietnam',
    showroomLocation: 'Nam Từ Liêm, Hà Nội',
    showroomContact: '024 3556 1234',
    sellerType: 'Nhà phân phối chính thức',
  },
  {
    id: 'p-009',
    name: 'Kệ phòng tắm Linea',
    category: 'Shelf',
    brand: 'Deens',
    sku: 'DNS-KPT-009',
    priceMin: 680_000,
    priceMax: 1_200_000,
    priceRange: '680.000đ – 1.200.000đ',
    material: 'Inox 304',
    finish: 'Chrome mờ',
    size: '40 × 12 × 1.2 cm',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80',
    availability: 'In Stock',
    suitableFor: ['Phòng tắm'],
    description: 'Kệ inox treo tường gọn nhẹ, chịu ẩm tốt, phù hợp để đồ trang trí hoặc đồ dùng vệ sinh.',
    style: 'Minimal',
    showroomName: 'Deens Lighting & Mirror',
    showroomLocation: 'Kim Mã, Hà Nội',
    showroomContact: '024 6688 5500',
    sellerType: 'Nhà phân phối chính thức',
  },
  {
    id: 'p-010',
    name: 'Phụ kiện treo khăn Kira',
    category: 'Accessories',
    brand: 'Grohe',
    sku: 'GRO-PTK-010',
    priceMin: 450_000,
    priceMax: 820_000,
    priceRange: '450.000đ – 820.000đ',
    material: 'Đồng thau mạ',
    finish: 'Vàng xước',
    image: 'https://images.unsplash.com/photo-1572635148818-ef6fd45eb394?w=600&q=80',
    availability: 'In Stock',
    suitableFor: ['Phòng tắm', 'Hotel'],
    description: 'Thanh treo khăn mạ vàng xước sang trọng, trọng tải 5kg, dễ lắp đặt.',
    style: 'Hotel',
    showroomName: 'LivLab Partner – Grohe Studio',
    showroomLocation: 'Hoàng Quốc Việt, Hà Nội',
    showroomContact: '024 3566 8888',
    sellerType: 'Showroom đối tác',
  },
] as Product[];

// ─── CONCEPTS ─────────────────────────────────────────────────────────────────

export const concepts: Concept[] = generatedConcepts;

// ─── MOCK LEADS ───────────────────────────────────────────────────────────────

export const mockLeads: Lead[] = [
  {
    id: 'l-001',
    requestCode: 'LLQ-2026-001',
    customerName: 'Nguyễn Anh Minh',
    phone: '+84912345678',
    email: 'anh.minh@gmail.com',
    roomType: 'Phòng tắm',
    roomSize: '5 m²',
    budgetRange: '30M–60M',
    style: 'Japandi',
    selectedConcept: 'Phòng tắm Japandi cho căn hộ',
    selectedProducts: [] as any,
    notes: 'Muốn phòng tắm yên tĩnh, ấm áp. Ưu tiên vật liệu tự nhiên.',
    timeline: '1–2 tháng',
    needsInstallation: true,
    consent: true,
    status: 'Mới',
    createdAt: '2026-06-05T09:30:00Z',
    estimatedValueMin: 45000000,
    estimatedValueMax: 50000000,
  },
  {
    id: 'l-002',
    requestCode: 'LLQ-2026-002',
    customerName: 'Trần Thanh Hương',
    phone: '+84978901234',
    email: 'thanh.huong@outlook.com',
    roomType: 'Phòng tắm',
    roomSize: '8 m²',
    budgetRange: '60M+',
    style: 'Hotel',
    selectedConcept: 'Phòng tắm phong cách khách sạn',
    selectedProducts: [] as any,
    notes: 'Muốn trải nghiệm 5 sao tại nhà. Ngân sách linh hoạt.',
    timeline: '3–6 tháng',
    needsInstallation: true,
    consent: true,
    status: 'Đã liên hệ',
    createdAt: '2026-06-04T14:15:00Z',
    estimatedValueMin: 78000000,
    estimatedValueMax: 90000000,
  },
  {
    id: 'l-003',
    requestCode: 'LLQ-2026-003',
    customerName: 'Lê Thị Thu Hà',
    phone: '+84857234567',
    email: undefined,
    roomType: 'Phòng khách',
    roomSize: '25 m²',
    budgetRange: '30M–60M',
    style: 'Warm Neutral',
    selectedConcept: 'Phòng khách tối giản ấm',
    selectedProducts: [] as any,
    notes: 'Mới chuyển vào căn hộ mới. Muốn không gian ấm cúng nhưng gọn.',
    timeline: 'Trong vòng 1 tháng',
    needsInstallation: false,
    consent: true,
    status: 'Đã báo giá',
    createdAt: '2026-06-03T11:00:00Z',
    estimatedValueMin: 32000000,
    estimatedValueMax: 35000000,
  },
  {
    id: 'l-004',
    requestCode: 'LLQ-2026-004',
    customerName: 'Phạm Quốc Bảo',
    phone: '+84821678901',
    email: 'quoc.bao@company.vn',
    roomType: 'Phòng tắm',
    roomSize: '3 m²',
    budgetRange: 'Under 30M',
    style: 'Minimal',
    selectedConcept: 'Phòng tắm căn hộ nhỏ',
    selectedProducts: [] as any,
    notes: 'Cải tạo phòng tắm nhỏ trong chung cư. Cần gói trọn gói.',
    timeline: 'Trong vòng 1 tháng',
    needsInstallation: true,
    consent: true,
    status: 'Đã chốt',
    createdAt: '2026-06-01T08:45:00Z',
    estimatedValueMin: 22000000,
    estimatedValueMax: 25000000,
  },
  {
    id: 'l-005',
    requestCode: 'LLQ-2026-005',
    customerName: 'Hoàng Minh Phúc',
    phone: '+84896345678',
    email: 'minh.phuc@mail.vn',
    roomType: 'Phòng tắm',
    roomSize: '4 m²',
    budgetRange: 'Under 30M',
    style: 'Minimal',
    selectedConcept: 'Phòng tắm tiết kiệm cho nhà cho thuê',
    selectedProducts: [] as any,
    notes: 'Thuê nhà, cần nâng cấp phòng tắm với chi phí hợp lý.',
    timeline: '2–3 tháng',
    needsInstallation: false,
    consent: true,
    status: 'Mới',
    createdAt: '2026-06-06T16:00:00Z',
    estimatedValueMin: 18000000,
    estimatedValueMax: 20000000,
  },
];

// ─── BLOG POSTS ───────────────────────────────────────────────────────────────

export const blogPosts: BlogPost[] = [
  {
    id: 'b-001',
    slug: '5-loi-mua-thiet-bi-ve-sinh',
    title: '5 lỗi thường gặp khi mua thiết bị vệ sinh cho phòng tắm nhỏ',
    excerpt: 'Nhiều gia đình chọn sai lavabo, vòi hoặc bồn cầu vì không tính đến kích thước phòng và tổng thể combo. Bài viết này giúp bạn tránh các lỗi phổ biến nhất.',
    content: 'Nội dung đầy đủ của bài viết số 1...',
    category: 'Thiết bị vệ sinh',
    image: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&q=80',
    readingTime: 5,
    publishedAt: '2026-06-01T08:00:00Z',
    tags: ['phòng tắm nhỏ', 'lavabo', 'mua sắm'],
  },
  {
    id: 'b-002',
    slug: 'combo-phong-tam-duoi-30-trieu',
    title: 'Combo phòng tắm dưới 30 triệu nên gồm những gì?',
    excerpt: 'Với ngân sách dưới 30 triệu, bạn vẫn có thể có một phòng tắm đẹp, đầy đủ thiết bị. Xem gợi ý combo hợp lý cho căn hộ và nhà thuê.',
    content: 'Nội dung đầy đủ của bài viết số 2...',
    category: 'Ngân sách',
    image: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=800&q=80',
    readingTime: 7,
    publishedAt: '2026-06-03T09:00:00Z',
    tags: ['combo', 'ngân sách', 'phòng tắm'],
  },
  {
    id: 'b-003',
    slug: 'chon-lavabo-voi-guong-dong-bo',
    title: 'Cách chọn lavabo, vòi và gương sao cho đồng bộ',
    excerpt: 'Ba thiết bị này cần có sự đồng bộ về phong cách, màu sắc và tỉ lệ. Bài viết hướng dẫn nguyên tắc cơ bản giúp phòng tắm trông có chủ ý hơn.',
    content: 'Nội dung đầy đủ của bài viết số 3...',
    category: 'Phòng tắm',
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
    readingTime: 6,
    publishedAt: '2026-06-05T08:00:00Z',
    tags: ['lavabo', 'vòi', 'gương', 'tư vấn'],
  },
  {
    id: 'b-004',
    slug: 'xem-concept-truoc-khi-bao-gia',
    title: 'Vì sao nên xem sản phẩm trong concept trước khi xin báo giá?',
    excerpt: 'Xem sản phẩm rời rạc sẽ rất khó hình dung tổng thể. LivLab cung cấp concept đã được phối hợp sẵn để bạn thấy toàn cảnh trước khi quyết định.',
    content: 'Nội dung đầy đủ của bài viết số 4...',
    category: 'Kinh nghiệm mua hàng',
    image: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&q=80',
    readingTime: 4,
    publishedAt: '2026-06-07T10:00:00Z',
    tags: ['concept', 'trải nghiệm', 'LivLab'],
  },
  {
    id: 'b-005',
    slug: 'checklist-cai-tao-phong-tam',
    title: 'Checklist cải tạo phòng tắm cho căn hộ cho thuê',
    excerpt: 'Trước khi bắt đầu cải tạo phòng tắm, hãy đảm bảo bạn đã chuẩn bị đủ 10 hạng mục cần thiết. Download checklist miễn phí từ LivLab.',
    content: 'Nội dung đầy đủ của bài viết số 5...',
    category: 'Cải tạo nhà',
    image: 'https://images.unsplash.com/photo-1615971677499-5467cbab01b0?w=800&q=80',
    readingTime: 8,
    publishedAt: '2026-06-08T08:00:00Z',
    tags: ['cải tạo', 'checklist', 'nhà cho thuê'],
  },
];

// ─── HELPERS ──────────────────────────────────────────────────────────────────

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getConceptBySlug(slug: string): Concept | undefined {
  return concepts.find((c) => c.slug === slug);
}

export function getConceptsContainingProduct(productId: string): Concept[] {
  return concepts.filter((c) => {
    const pIds = c.productIds || [];
    return pIds.includes(productId);
  });
}

export function getBlogPostBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find((b) => b.slug === slug);
}
