import { Product } from './types';

export const visualProducts: Product[] = [
  {
    "id": "prod-bas-001",
    "name": "Chậu Rửa Đặt Bàn Hình Oval Minimal",
    "category": "Basin",
    "brand": "Inax",
    "sku": "INAX-AL-299V",
    "priceMin": 2200000,
    "priceMax": 2200000,
    "priceRange": "2.200.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1620626011761-996317b8d101?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Chậu Rửa Đặt Bàn Hình Oval Minimal chính hãng từ Inax, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Inax Partner",
    "commerceType": "Quote-based commerce",
    "style": "Minimal"
  },
  {
    "id": "prod-bas-002",
    "name": "Chậu Rửa Âm Bàn Tròn Bán Điển",
    "category": "Basin",
    "brand": "TOTO",
    "sku": "TOTO-LW1536V",
    "priceMin": 1850000,
    "priceMax": 1850000,
    "priceRange": "1.850.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Chậu Rửa Âm Bàn Tròn Bán Điển chính hãng từ TOTO, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "TOTO Partner",
    "commerceType": "Quote-based commerce",
    "style": "Modern"
  },
  {
    "id": "prod-bas-003",
    "name": "Lavabo Treo Tường Nhỏ Gọn",
    "category": "Basin",
    "brand": "Viglacera",
    "sku": "VIG-V23",
    "priceMin": 650000,
    "priceMax": 650000,
    "priceRange": "650.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://plus.unsplash.com/premium_photo-1661877303180-19a028c21048?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Lavabo Treo Tường Nhỏ Gọn chính hãng từ Viglacera, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Viglacera Partner",
    "commerceType": "Quote-based commerce",
    "style": "Budget"
  },
  {
    "id": "prod-bas-004",
    "name": "Chậu Rửa Đặt Bàn Đá Cuội",
    "category": "Basin",
    "brand": "Bancoot",
    "sku": "BC-STON-01",
    "priceMin": 3500000,
    "priceMax": 3500000,
    "priceRange": "3.500.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1620626011761-996317b8d101?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Chậu Rửa Đặt Bàn Đá Cuội chính hãng từ Bancoot, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Bancoot Partner",
    "commerceType": "Quote-based commerce",
    "style": "Boutique"
  },
  {
    "id": "prod-bas-005",
    "name": "Chậu Rửa Vuông Cạnh Sắc Nét",
    "category": "Basin",
    "brand": "Kohler",
    "sku": "KOH-SQ-11",
    "priceMin": 4200000,
    "priceMax": 4200000,
    "priceRange": "4.200.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Chậu Rửa Vuông Cạnh Sắc Nét chính hãng từ Kohler, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Kohler Partner",
    "commerceType": "Quote-based commerce",
    "style": "Luxury"
  },
  {
    "id": "prod-bas-006",
    "name": "Lavabo Góc Tròn Tiết Kiệm Không Gian",
    "category": "Basin",
    "brand": "Caesar",
    "sku": "CAE-C22",
    "priceMin": 850000,
    "priceMax": 850000,
    "priceRange": "850.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1620626011761-996317b8d101?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Lavabo Góc Tròn Tiết Kiệm Không Gian chính hãng từ Caesar, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Caesar Partner",
    "commerceType": "Quote-based commerce",
    "style": "Compact"
  },
  {
    "id": "prod-bas-007",
    "name": "Chậu Đặt Bàn Gốm Sứ Hoa Văn",
    "category": "Basin",
    "brand": "Bát Tràng",
    "sku": "BT-CER-99",
    "priceMin": 1200000,
    "priceMax": 1200000,
    "priceRange": "1.200.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://plus.unsplash.com/premium_photo-1661877303180-19a028c21048?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Chậu Đặt Bàn Gốm Sứ Hoa Văn chính hãng từ Bát Tràng, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Bát Tràng Partner",
    "commerceType": "Quote-based commerce",
    "style": "Boutique"
  },
  {
    "id": "prod-bas-008",
    "name": "Chậu Âm Bàn Chữ Nhật Siêu Lớn",
    "category": "Basin",
    "brand": "Inax",
    "sku": "INAX-AL-555V",
    "priceMin": 2900000,
    "priceMax": 2900000,
    "priceRange": "2.900.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Chậu Âm Bàn Chữ Nhật Siêu Lớn chính hãng từ Inax, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Inax Partner",
    "commerceType": "Quote-based commerce",
    "style": "Modern"
  },
  {
    "id": "prod-bas-009",
    "name": "Lavabo Bán Âm Bàn",
    "category": "Basin",
    "brand": "TOTO",
    "sku": "TOTO-LW644",
    "priceMin": 3100000,
    "priceMax": 3100000,
    "priceRange": "3.100.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1620626011761-996317b8d101?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Lavabo Bán Âm Bàn chính hãng từ TOTO, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "TOTO Partner",
    "commerceType": "Quote-based commerce",
    "style": "Modern"
  },
  {
    "id": "prod-fau-010",
    "name": "Vòi Chậu Cổ Cao Phủ Đen Nhám",
    "category": "Faucet",
    "brand": "Moen",
    "sku": "MOEN-B-6702",
    "priceMin": 3200000,
    "priceMax": 3200000,
    "priceRange": "3.200.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1584622781867-1c1ac2d159be?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Vòi Chậu Cổ Cao Phủ Đen Nhám chính hãng từ Moen, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Moen Partner",
    "commerceType": "Quote-based commerce",
    "style": "Industrial"
  },
  {
    "id": "prod-fau-011",
    "name": "Vòi Lavabo Âm Tường Minimalist",
    "category": "Faucet",
    "brand": "Grohe",
    "sku": "GROHE-AM-100",
    "priceMin": 6800000,
    "priceMax": 6800000,
    "priceRange": "6.800.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1585058177435-098d626889eb?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Vòi Lavabo Âm Tường Minimalist chính hãng từ Grohe, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Grohe Partner",
    "commerceType": "Quote-based commerce",
    "style": "Luxury"
  },
  {
    "id": "prod-fau-012",
    "name": "Vòi Lavabo Nóng Lạnh Cơ Bản",
    "category": "Faucet",
    "brand": "Inax",
    "sku": "INAX-LFV-1112S",
    "priceMin": 1100000,
    "priceMax": 1100000,
    "priceRange": "1.100.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1584622781867-1c1ac2d159be?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Vòi Lavabo Nóng Lạnh Cơ Bản chính hãng từ Inax, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Inax Partner",
    "commerceType": "Quote-based commerce",
    "style": "Budget"
  },
  {
    "id": "prod-fau-013",
    "name": "Vòi Chậu Cảm Ứng Tự Động",
    "category": "Faucet",
    "brand": "TOTO",
    "sku": "TOTO-TEN40AW",
    "priceMin": 8500000,
    "priceMax": 8500000,
    "priceRange": "8.500.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1585058177435-098d626889eb?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Vòi Chậu Cảm Ứng Tự Động chính hãng từ TOTO, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "TOTO Partner",
    "commerceType": "Quote-based commerce",
    "style": "Modern"
  },
  {
    "id": "prod-fau-014",
    "name": "Vòi Rửa Đồng Cổ Điển",
    "category": "Faucet",
    "brand": "Kanly",
    "sku": "KAN-BR-01",
    "priceMin": 2400000,
    "priceMax": 2400000,
    "priceRange": "2.400.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1584622781867-1c1ac2d159be?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Vòi Rửa Đồng Cổ Điển chính hãng từ Kanly, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Kanly Partner",
    "commerceType": "Quote-based commerce",
    "style": "Boutique"
  },
  {
    "id": "prod-fau-015",
    "name": "Vòi Lavabo Cổ Thấp Trắng Nhám",
    "category": "Faucet",
    "brand": "Viglacera",
    "sku": "VIG-VG102",
    "priceMin": 1400000,
    "priceMax": 1400000,
    "priceRange": "1.400.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1585058177435-098d626889eb?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Vòi Lavabo Cổ Thấp Trắng Nhám chính hãng từ Viglacera, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Viglacera Partner",
    "commerceType": "Quote-based commerce",
    "style": "Minimal"
  },
  {
    "id": "prod-fau-016",
    "name": "Vòi Chậu Kèm Dây Rút",
    "category": "Faucet",
    "brand": "Kohler",
    "sku": "KOH-K102",
    "priceMin": 5600000,
    "priceMax": 5600000,
    "priceRange": "5.600.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1584622781867-1c1ac2d159be?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Vòi Chậu Kèm Dây Rút chính hãng từ Kohler, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Kohler Partner",
    "commerceType": "Quote-based commerce",
    "style": "Modern"
  },
  {
    "id": "prod-toi-017",
    "name": "Bồn Cầu Thông Minh Liền Khối",
    "category": "Toilet",
    "brand": "TOTO",
    "sku": "TOTO-NEOREST-X",
    "priceMin": 45000000,
    "priceMax": 45000000,
    "priceRange": "45.000.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Bồn Cầu Thông Minh Liền Khối chính hãng từ TOTO, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "TOTO Partner",
    "commerceType": "Quote-based commerce",
    "style": "Hotel"
  },
  {
    "id": "prod-toi-018",
    "name": "Bồn Cầu Một Khối Xả Xoáy",
    "category": "Toilet",
    "brand": "Inax",
    "sku": "INAX-1050",
    "priceMin": 7500000,
    "priceMax": 7500000,
    "priceRange": "7.500.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1564540574859-0dfb63985953?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Bồn Cầu Một Khối Xả Xoáy chính hãng từ Inax, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Inax Partner",
    "commerceType": "Quote-based commerce",
    "style": "Modern"
  },
  {
    "id": "prod-toi-019",
    "name": "Bồn Cầu Hai Khối Siêu Tiết Kiệm",
    "category": "Toilet",
    "brand": "Viglacera",
    "sku": "VIG-VI66",
    "priceMin": 2200000,
    "priceMax": 2200000,
    "priceRange": "2.200.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Bồn Cầu Hai Khối Siêu Tiết Kiệm chính hãng từ Viglacera, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Viglacera Partner",
    "commerceType": "Quote-based commerce",
    "style": "Budget"
  },
  {
    "id": "prod-toi-020",
    "name": "Bồn Cầu Treo Tường Kèm Két Nước Âm",
    "category": "Toilet",
    "brand": "Grohe",
    "sku": "GROHE-WALL-01",
    "priceMin": 14000000,
    "priceMax": 14000000,
    "priceRange": "14.000.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1564540574859-0dfb63985953?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Bồn Cầu Treo Tường Kèm Két Nước Âm chính hãng từ Grohe, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Grohe Partner",
    "commerceType": "Quote-based commerce",
    "style": "Minimal"
  },
  {
    "id": "prod-toi-021",
    "name": "Bồn Cầu Thông Minh Màu Đen",
    "category": "Toilet",
    "brand": "Kohler",
    "sku": "KOH-NUMI-B",
    "priceMin": 95000000,
    "priceMax": 95000000,
    "priceRange": "95.000.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Bồn Cầu Thông Minh Màu Đen chính hãng từ Kohler, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Kohler Partner",
    "commerceType": "Quote-based commerce",
    "style": "Luxury"
  },
  {
    "id": "prod-toi-022",
    "name": "Bồn Cầu Cổ Điển Két Nước Cao",
    "category": "Toilet",
    "brand": "Burlington",
    "sku": "BUR-HIGH-01",
    "priceMin": 18000000,
    "priceMax": 18000000,
    "priceRange": "18.000.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1564540574859-0dfb63985953?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Bồn Cầu Cổ Điển Két Nước Cao chính hãng từ Burlington, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Burlington Partner",
    "commerceType": "Quote-based commerce",
    "style": "Boutique"
  },
  {
    "id": "prod-sho-023",
    "name": "Sen Cây Chỉnh Nhiệt Độ Phím Đàn",
    "category": "Shower",
    "brand": "Kohler",
    "sku": "K-SH-8822",
    "priceMin": 12500000,
    "priceMax": 12500000,
    "priceRange": "12.500.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1620626012488-825fb4dcbe65?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Sen Cây Chỉnh Nhiệt Độ Phím Đàn chính hãng từ Kohler, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Kohler Partner",
    "commerceType": "Quote-based commerce",
    "style": "Luxury"
  },
  {
    "id": "prod-sho-024",
    "name": "Sen Tay Tăng Áp Cơ Bản",
    "category": "Shower",
    "brand": "Caesar",
    "sku": "CAE-S120",
    "priceMin": 450000,
    "priceMax": 450000,
    "priceRange": "450.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1584622781867-1c1ac2d159be?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Sen Tay Tăng Áp Cơ Bản chính hãng từ Caesar, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Caesar Partner",
    "commerceType": "Quote-based commerce",
    "style": "Budget"
  },
  {
    "id": "prod-sho-025",
    "name": "Sen Tắm Âm Tường 3 Chế Độ",
    "category": "Shower",
    "brand": "Grohe",
    "sku": "GROHE-SMART-3",
    "priceMin": 24000000,
    "priceMax": 24000000,
    "priceRange": "24.000.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1620626012488-825fb4dcbe65?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Sen Tắm Âm Tường 3 Chế Độ chính hãng từ Grohe, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Grohe Partner",
    "commerceType": "Quote-based commerce",
    "style": "Hotel"
  },
  {
    "id": "prod-sho-026",
    "name": "Sen Cây Đồng Cổ Điển",
    "category": "Shower",
    "brand": "Kanly",
    "sku": "KAN-SH-BR",
    "priceMin": 4500000,
    "priceMax": 4500000,
    "priceRange": "4.500.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1620626012488-825fb4dcbe65?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Sen Cây Đồng Cổ Điển chính hãng từ Kanly, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Kanly Partner",
    "commerceType": "Quote-based commerce",
    "style": "Boutique"
  },
  {
    "id": "prod-sho-027",
    "name": "Sen Tắm Nhiệt Độ An Toàn Cảm Biến",
    "category": "Shower",
    "brand": "TOTO",
    "sku": "TOTO-TMNW40",
    "priceMin": 9200000,
    "priceMax": 9200000,
    "priceRange": "9.200.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1620626012488-825fb4dcbe65?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Sen Tắm Nhiệt Độ An Toàn Cảm Biến chính hãng từ TOTO, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "TOTO Partner",
    "commerceType": "Quote-based commerce",
    "style": "Modern"
  },
  {
    "id": "prod-sho-028",
    "name": "Sen Tắm Vuông Inox 304",
    "category": "Shower",
    "brand": "Inax",
    "sku": "INAX-BFV-3415T",
    "priceMin": 5800000,
    "priceMax": 5800000,
    "priceRange": "5.800.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1620626012488-825fb4dcbe65?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Sen Tắm Vuông Inox 304 chính hãng từ Inax, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Inax Partner",
    "commerceType": "Quote-based commerce",
    "style": "Minimal"
  },
  {
    "id": "prod-mir-029",
    "name": "Gương LED Tròn Cảm Ứng Chống Đọng Hơi Nước",
    "category": "Mirror",
    "brand": "Navado",
    "sku": "NAV-R80",
    "priceMin": 2100000,
    "priceMax": 2100000,
    "priceRange": "2.100.000đ",
    "priceUnit": "cái",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Gương LED Tròn Cảm Ứng Chống Đọng Hơi Nước chính hãng từ Navado, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Navado Partner",
    "commerceType": "Quote-based commerce",
    "style": "Modern"
  },
  {
    "id": "prod-mir-030",
    "name": "Gương Chữ Nhật Viền Đen Nhôm",
    "category": "Mirror",
    "brand": "Dantalux",
    "sku": "DAN-REC-6080",
    "priceMin": 950000,
    "priceMax": 950000,
    "priceRange": "950.000đ",
    "priceUnit": "cái",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Gương Chữ Nhật Viền Đen Nhôm chính hãng từ Dantalux, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Dantalux Partner",
    "commerceType": "Quote-based commerce",
    "style": "Industrial"
  },
  {
    "id": "prod-mir-031",
    "name": "Gương Tròn Dây Da Treo",
    "category": "Mirror",
    "brand": "Handmade",
    "sku": "HM-LEATHER-R60",
    "priceMin": 750000,
    "priceMax": 750000,
    "priceRange": "750.000đ",
    "priceUnit": "cái",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Gương Tròn Dây Da Treo chính hãng từ Handmade, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Handmade Partner",
    "commerceType": "Quote-based commerce",
    "style": "Boutique"
  },
  {
    "id": "prod-mir-032",
    "name": "Gương LED Viền Gỗ Sồi",
    "category": "Mirror",
    "brand": "Navado",
    "sku": "NAV-OAK-LED",
    "priceMin": 2800000,
    "priceMax": 2800000,
    "priceRange": "2.800.000đ",
    "priceUnit": "cái",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Gương LED Viền Gỗ Sồi chính hãng từ Navado, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Navado Partner",
    "commerceType": "Quote-based commerce",
    "style": "Japandi"
  },
  {
    "id": "prod-mir-033",
    "name": "Gương Oval Đèn Hắt Sau",
    "category": "Mirror",
    "brand": "TOTO",
    "sku": "TOTO-YM6090A",
    "priceMin": 3500000,
    "priceMax": 3500000,
    "priceRange": "3.500.000đ",
    "priceUnit": "cái",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Gương Oval Đèn Hắt Sau chính hãng từ TOTO, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "TOTO Partner",
    "commerceType": "Quote-based commerce",
    "style": "Luxury"
  },
  {
    "id": "prod-cab-034",
    "name": "Tủ Lavabo Treo Tường Gỗ Tự Nhiên Vân Sồi",
    "category": "Cabinet",
    "brand": "Vicostone",
    "sku": "CAB-OAK-08",
    "priceMin": 5500000,
    "priceMax": 5500000,
    "priceRange": "5.500.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Tủ Lavabo Treo Tường Gỗ Tự Nhiên Vân Sồi chính hãng từ Vicostone, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Vicostone Partner",
    "commerceType": "Quote-based commerce",
    "style": "Japandi"
  },
  {
    "id": "prod-cab-035",
    "name": "Tủ Chậu PVC Chống Nước Tuyệt Đối",
    "category": "Cabinet",
    "brand": "DADA",
    "sku": "DADA-PVC-60",
    "priceMin": 3200000,
    "priceMax": 3200000,
    "priceRange": "3.200.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Tủ Chậu PVC Chống Nước Tuyệt Đối chính hãng từ DADA, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "DADA Partner",
    "commerceType": "Quote-based commerce",
    "style": "Modern"
  },
  {
    "id": "prod-cab-036",
    "name": "Tủ Lavabo Đặt Sàn Tân Cổ Điển",
    "category": "Cabinet",
    "brand": "Moen",
    "sku": "MOEN-CAB-CL",
    "priceMin": 8500000,
    "priceMax": 8500000,
    "priceRange": "8.500.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Tủ Lavabo Đặt Sàn Tân Cổ Điển chính hãng từ Moen, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Moen Partner",
    "commerceType": "Quote-based commerce",
    "style": "Boutique"
  },
  {
    "id": "prod-cab-037",
    "name": "Tủ Chậu Bán Nguyệt Siêu Nhỏ",
    "category": "Cabinet",
    "brand": "Caesar",
    "sku": "CAE-MINI-C",
    "priceMin": 2100000,
    "priceMax": 2100000,
    "priceRange": "2.100.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Tủ Chậu Bán Nguyệt Siêu Nhỏ chính hãng từ Caesar, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Caesar Partner",
    "commerceType": "Quote-based commerce",
    "style": "Compact"
  },
  {
    "id": "prod-cab-038",
    "name": "Hệ Tủ Lavabo Kép Khách Sạn",
    "category": "Cabinet",
    "brand": "Kohler",
    "sku": "KOH-DB-CAB",
    "priceMin": 18000000,
    "priceMax": 18000000,
    "priceRange": "18.000.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Hệ Tủ Lavabo Kép Khách Sạn chính hãng từ Kohler, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Kohler Partner",
    "commerceType": "Quote-based commerce",
    "style": "Hotel"
  },
  {
    "id": "prod-til-039",
    "name": "Gạch Thẻ Trắng Men Bóng Cổ Điển",
    "category": "Tiles",
    "brand": "Đồng Tâm",
    "sku": "DT-SUBWAY-W",
    "priceMin": 320000,
    "priceMax": 320000,
    "priceRange": "320.000đ",
    "priceUnit": "m2",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Gạch Thẻ Trắng Men Bóng Cổ Điển chính hãng từ Đồng Tâm, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Đồng Tâm Partner",
    "commerceType": "Quote-based commerce",
    "style": "Minimal"
  },
  {
    "id": "prod-til-040",
    "name": "Gạch Lát Nền Giả Gỗ Chống Trơn",
    "category": "Tiles",
    "brand": "Prime",
    "sku": "PR-WOOD-1560",
    "priceMin": 250000,
    "priceMax": 250000,
    "priceRange": "250.000đ",
    "priceUnit": "m2",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Gạch Lát Nền Giả Gỗ Chống Trơn chính hãng từ Prime, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Prime Partner",
    "commerceType": "Quote-based commerce",
    "style": "Japandi"
  },
  {
    "id": "prod-til-041",
    "name": "Gạch Lát Nền Terrazzo Xám",
    "category": "Tiles",
    "brand": "Taicera",
    "sku": "TC-TERZ-6060",
    "priceMin": 420000,
    "priceMax": 420000,
    "priceRange": "420.000đ",
    "priceUnit": "m2",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Gạch Lát Nền Terrazzo Xám chính hãng từ Taicera, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Taicera Partner",
    "commerceType": "Quote-based commerce",
    "style": "Modern"
  },
  {
    "id": "prod-til-042",
    "name": "Gạch Bông Men Trang Trí",
    "category": "Tiles",
    "brand": "Secoin",
    "sku": "SEC-CEM-20",
    "priceMin": 650000,
    "priceMax": 650000,
    "priceRange": "650.000đ",
    "priceUnit": "m2",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Gạch Bông Men Trang Trí chính hãng từ Secoin, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Secoin Partner",
    "commerceType": "Quote-based commerce",
    "style": "Boutique"
  },
  {
    "id": "prod-til-043",
    "name": "Gạch Ốp Tường Marble Khổ Lớn",
    "category": "Tiles",
    "brand": "Vietceramics",
    "sku": "VC-MAR-80160",
    "priceMin": 1200000,
    "priceMax": 1200000,
    "priceRange": "1.200.000đ",
    "priceUnit": "m2",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Gạch Ốp Tường Marble Khổ Lớn chính hãng từ Vietceramics, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Vietceramics Partner",
    "commerceType": "Quote-based commerce",
    "style": "Luxury"
  },
  {
    "id": "prod-acc-044",
    "name": "Bộ Phụ Kiện Phòng Tắm 5 Món Đen Nhám",
    "category": "Accessories",
    "brand": "Imex",
    "sku": "IMEX-BLK-5P",
    "priceMin": 1850000,
    "priceMax": 1850000,
    "priceRange": "1.850.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1584622781867-1c1ac2d159be?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Bộ Phụ Kiện Phòng Tắm 5 Món Đen Nhám chính hãng từ Imex, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Imex Partner",
    "commerceType": "Quote-based commerce",
    "style": "Industrial"
  },
  {
    "id": "prod-acc-045",
    "name": "Thanh Treo Khăn Nóng Sưởi Khô",
    "category": "Accessories",
    "brand": "Grohe",
    "sku": "GROHE-HEAT-T",
    "priceMin": 8500000,
    "priceMax": 8500000,
    "priceRange": "8.500.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1584622781867-1c1ac2d159be?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Thanh Treo Khăn Nóng Sưởi Khô chính hãng từ Grohe, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Grohe Partner",
    "commerceType": "Quote-based commerce",
    "style": "Hotel"
  },
  {
    "id": "prod-acc-046",
    "name": "Lô Giấy Vệ Sinh Inox Bóng",
    "category": "Accessories",
    "brand": "TOTO",
    "sku": "TOTO-PAPER-S",
    "priceMin": 450000,
    "priceMax": 450000,
    "priceRange": "450.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1584622781867-1c1ac2d159be?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Lô Giấy Vệ Sinh Inox Bóng chính hãng từ TOTO, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "TOTO Partner",
    "commerceType": "Quote-based commerce",
    "style": "Modern"
  },
  {
    "id": "prod-acc-047",
    "name": "Kệ Góc Kính Cường Lực",
    "category": "Accessories",
    "brand": "Inax",
    "sku": "INAX-GLASS-C",
    "priceMin": 320000,
    "priceMax": 320000,
    "priceRange": "320.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1584622781867-1c1ac2d159be?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Kệ Góc Kính Cường Lực chính hãng từ Inax, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Inax Partner",
    "commerceType": "Quote-based commerce",
    "style": "Budget"
  },
  {
    "id": "prod-acc-048",
    "name": "Bộ Móc Treo Áo Cổ Điển Bằng Đồng",
    "category": "Accessories",
    "brand": "Kanly",
    "sku": "KAN-HOOK-BR",
    "priceMin": 650000,
    "priceMax": 650000,
    "priceRange": "650.000đ",
    "priceUnit": "bộ",
    "material": "Vật liệu cao cấp",
    "finish": "Tiêu chuẩn",
    "dimensions": "Tuỳ chỉnh",
    "installationType": "Mặc định",
    "warranty": "Bảo hành chính hãng",
    "image": "https://images.unsplash.com/photo-1584622781867-1c1ac2d159be?w=800&q=80",
    "imageVerified": false,
    "availability": "In Stock",
    "status": "Còn hàng",
    "description": "Sản phẩm Bộ Móc Treo Áo Cổ Điển Bằng Đồng chính hãng từ Kanly, phù hợp cho không gian phòng tắm sang trọng. Mức giá tham khảo, chi tiết vui lòng thêm vào giỏ báo giá.",
    "features": [
      "Thiết kế đẹp mắt",
      "Độ bền cao",
      "Dễ dàng lắp đặt"
    ],
    "technicalSpecs": [
      "Sản xuất theo tiêu chuẩn quốc tế",
      "Phù hợp mọi không gian"
    ],
    "showroomName": "Hệ thống Showroom Đối Tác",
    "showroomLocation": "Hà Nội & TP.HCM",
    "sellerType": "Showroom đối tác",
    "soldBy": "LivLab",
    "fulfilledBy": "Kanly Partner",
    "commerceType": "Quote-based commerce",
    "style": "Boutique"
  }
];

export async function seedVisualProducts(force: boolean = false): Promise<void> {
  const currentProductsStr = typeof window !== 'undefined' ? localStorage.getItem('livlab_products') : null;
  const currentProducts: Product[] = currentProductsStr ? JSON.parse(currentProductsStr) : [];

  let shouldSeed = force;

  if (!shouldSeed && typeof window !== 'undefined') {
    if (currentProducts.length < 30) {
      shouldSeed = true;
    } else {
      const placeholders = currentProducts.filter(p => p.image.includes('placeholder'));
      if (placeholders.length / currentProducts.length > 0.5) {
        shouldSeed = true;
      }
    }
  }

  if (shouldSeed && typeof window !== 'undefined') {
    localStorage.setItem('livlab_products', JSON.stringify(visualProducts));
    console.log('[LivLab] Auto-seeded visual products for Phase 2 e-commerce catalogue.');
  }
}
