import { Concept, Hotspot } from './types';

export const visualConcepts: Concept[] = [
  // A. BATHROOM CONCEPTS (18 concepts)
  {
    id: "vc-bath-1",
    slug: "phong-tam-can-ho-nho-duoi-4m2",
    title: "Phòng tắm căn hộ nhỏ dưới 4m²",
    roomType: "Phòng tắm",
    style: "Compact",
    budgetRange: "Dưới 30 triệu",
    areaSize: "3-4m²",
    shortDescription: "Concept demo",
    description: "Giải pháp tiết kiệm không gian với thiết bị vệ sinh nhỏ gọn, thông minh.",
    longDescription: "Không gian phòng tắm nhỏ nhưng vẫn đầy đủ tiện nghi với bồn cầu nguyên khối gọn gàng, tủ lavabo tích hợp không gian lưu trữ và gương LED giúp ăn gian diện tích. Tông màu sáng làm không gian có cảm giác rộng rãi hơn.",
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=1080&q=80",
    imageAlt: "Phòng tắm nhỏ gọn cho căn hộ",
    productIds: ["v_lavabo_5", "v_faucet_1", "v_toilet_4", "v_shower_2", "v_mirror_3", "v_cabinet_2"],
    hotspots: [
      { id: "hs-1-1", productId: "v_mirror_3", x: 52, y: 28, label: "Gương LED" },
      { id: "hs-1-2", productId: "v_lavabo_5", x: 50, y: 55, label: "Lavabo" },
      { id: "hs-1-3", productId: "v_cabinet_2", x: 48, y: 70, label: "Tủ Lavabo" },
      { id: "hs-1-4", productId: "v_shower_2", x: 22, y: 35, label: "Sen tắm" },
      { id: "hs-1-5", productId: "v_toilet_4", x: 76, y: 62, label: "Bồn cầu" }
    ],
    whyItWorks: ["Thiết kế nhỏ gọn", "Tối ưu lưu trữ", "Màu sắc sáng"],
    productCount: 6,
    suitableFor: ["Căn hộ nhỏ", "Nhà phố hẻm"],
    painPoints: ["Không gian chật hẹp", "Thiếu chỗ chứa đồ"],
    keyProducts: ["Tủ lavabo mini", "Gương LED tạo hiệu ứng rộng"],
    estimatedBudgetMin: 12000000,
    estimatedBudgetMax: 20000000,
    sourceNote: "Ảnh concept minh hoạ"
  },
  {
    id: "vc-bath-2",
    slug: "phong-tam-japandi-can-ho",
    title: "Phòng tắm Japandi cho căn hộ",
    roomType: "Phòng tắm",
    style: "Japandi",
    budgetRange: "30–60 triệu",
    areaSize: "4-6m²",
    shortDescription: "Concept demo",
    description: "Sự giao thoa hoàn hảo giữa phong cách Nhật Bản và Bắc Âu ấm áp.",
    longDescription: "Tông màu gỗ mộc mạc kết hợp cùng sứ trắng tinh khôi và ánh sáng vàng dịu mang lại cảm giác thiền định, thư giãn ngay trong chính ngôi nhà của bạn.",
    image: "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=1080&q=80",
    imageAlt: "Phòng tắm Japandi",
    productIds: ["v_lavabo_7", "v_faucet_6", "v_toilet_7", "v_shower_6", "v_mirror_6", "v_cabinet_4"],
    hotspots: [
      { id: "hs-2-1", productId: "v_mirror_6", x: 52, y: 28, label: "Gương LED vân gỗ" },
      { id: "hs-2-2", productId: "v_lavabo_7", x: 50, y: 55, label: "Lavabo đặt bàn" },
      { id: "hs-2-3", productId: "v_cabinet_4", x: 48, y: 70, label: "Tủ Lavabo vân sồi" },
      { id: "hs-2-4", productId: "v_shower_6", x: 22, y: 35, label: "Sen cây mạ đen" },
      { id: "hs-2-5", productId: "v_toilet_7", x: 76, y: 62, label: "Bồn cầu điện tử" }
    ],
    whyItWorks: ["Cảm giác ấm cúng", "Vật liệu tự nhiên", "Dễ dàng vệ sinh"],
    productCount: 6,
    suitableFor: ["Căn hộ 2PN", "Người yêu thiên nhiên"],
    painPoints: ["Phòng tắm lạnh lẽo", "Thiếu điểm nhấn thư giãn"],
    keyProducts: ["Tủ lavabo vân gỗ", "Sen tắm mờ"],
    estimatedBudgetMin: 25000000,
    estimatedBudgetMax: 45000000,
    sourceNote: "Ảnh concept minh hoạ"
  },
  {
    id: "vc-bath-3",
    slug: "phong-tam-phong-cach-khach-san",
    title: "Phòng tắm phong cách khách sạn",
    roomType: "Phòng tắm",
    style: "Hotel",
    budgetRange: "Trên 60 triệu",
    areaSize: "6-10m²",
    shortDescription: "Concept demo",
    description: "Tận hưởng không gian 5 sao đẳng cấp mỗi ngày.",
    longDescription: "Thiết kế sử dụng gạch vân đá cẩm thạch sang trọng, sen cây nhiệt độ cao cấp và bồn cầu thông minh, đem lại trải nghiệm chăm sóc bản thân đỉnh cao như đang nghỉ dưỡng.",
    image: "https://images.unsplash.com/photo-1507652313656-b14ef9c5f4ba?w=1080&q=80",
    imageAlt: "Phòng tắm khách sạn sang trọng",
    productIds: ["v_lavabo_8", "v_faucet_9", "v_toilet_8", "v_shower_8", "v_mirror_7", "v_cabinet_5", "v_tile_2"],
    hotspots: [
      { id: "hs-3-1", productId: "v_mirror_7", x: 50, y: 30, label: "Gương LED âm tường" },
      { id: "hs-3-2", productId: "v_lavabo_8", x: 50, y: 55, label: "Chậu rửa mặt" },
      { id: "hs-3-3", productId: "v_shower_8", x: 20, y: 40, label: "Sen cây nhiệt độ" },
      { id: "hs-3-4", productId: "v_toilet_8", x: 80, y: 65, label: "Bồn cầu thông minh" },
      { id: "hs-3-5", productId: "v_tile_2", x: 15, y: 80, label: "Gạch vân đá Marble" }
    ],
    whyItWorks: ["Sang trọng", "Trải nghiệm thư giãn", "Đồng bộ cao"],
    productCount: 7,
    suitableFor: ["Villa", "Penthouse", "Căn hộ cao cấp"],
    painPoints: ["Trải nghiệm tắm kém thoải mái"],
    keyProducts: ["Bồn cầu thông minh", "Sen cây nhiệt độ", "Gạch vân đá"],
    estimatedBudgetMin: 65000000,
    estimatedBudgetMax: 120000000,
    sourceNote: "Ảnh concept minh hoạ"
  },
  {
    id: "vc-bath-4",
    slug: "phong-tam-tiet-kiem-cho-nha-cho-thue",
    title: "Phòng tắm tiết kiệm cho nhà cho thuê",
    roomType: "Phòng tắm",
    style: "Budget",
    budgetRange: "Dưới 20 triệu",
    areaSize: "3-5m²",
    shortDescription: "Concept demo",
    description: "Tối ưu chi phí nhưng vẫn đảm bảo thẩm mỹ và độ bền.",
    longDescription: "Sử dụng các thiết bị sứ vệ sinh cơ bản từ các thương hiệu uy tín như Viglacera, Caesar... đảm bảo độ bền cao, chống hỏng hóc, dễ dàng bảo trì và thay thế cho khách thuê.",
    image: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=1080&q=80",
    imageAlt: "Phòng tắm nhà cho thuê",
    productIds: ["v_lavabo_1", "v_faucet_3", "v_toilet_1", "v_shower_1", "v_mirror_1", "v_acc_1"],
    hotspots: [
      { id: "hs-4-1", productId: "v_mirror_1", x: 50, y: 30, label: "Gương soi" },
      { id: "hs-4-2", productId: "v_lavabo_1", x: 50, y: 55, label: "Lavabo treo tường" },
      { id: "hs-4-3", productId: "v_faucet_3", x: 50, y: 48, label: "Vòi lạnh" },
      { id: "hs-4-4", productId: "v_shower_1", x: 20, y: 40, label: "Sen tắm cầm tay" },
      { id: "hs-4-5", productId: "v_toilet_1", x: 80, y: 65, label: "Bồn cầu 2 khối" }
    ],
    whyItWorks: ["Chi phí thấp", "Độ bền cao", "Dễ bảo trì"],
    productCount: 6,
    suitableFor: ["Nhà cho thuê", "Phòng trọ cao cấp"],
    painPoints: ["Thiết bị nhanh hỏng", "Khó thay thế"],
    keyProducts: ["Bồn cầu 2 khối cơ bản", "Lavabo treo tường"],
    estimatedBudgetMin: 5000000,
    estimatedBudgetMax: 10000000,
    sourceNote: "Ảnh concept minh hoạ"
  },
  {
    id: "vc-bath-5",
    slug: "phong-tam-premium-master",
    title: "Phòng tắm premium master",
    roomType: "Phòng tắm",
    style: "Luxury",
    budgetRange: "Trên 60 triệu",
    areaSize: "8-15m²",
    shortDescription: "Concept demo",
    description: "Không gian master đẳng cấp với bồn tắm độc lập.",
    longDescription: "Sự kết hợp hoàn hảo giữa không gian rộng lớn, bồn tắm độc lập sang trọng và hệ thống sen cây massage, biến phòng tắm thành một Spa thu nhỏ tại gia.",
    image: "https://images.unsplash.com/photo-1595514535315-2a25598816cb?w=1080&q=80",
    imageAlt: "Phòng tắm Master sang trọng",
    productIds: ["v_lavabo_8", "v_faucet_8", "v_toilet_10", "v_shower_9", "v_mirror_8", "v_tile_5", "v_acc_7"],
    hotspots: [
      { id: "hs-5-1", productId: "v_mirror_8", x: 50, y: 30, label: "Gương LED thông minh" },
      { id: "hs-5-2", productId: "v_lavabo_8", x: 50, y: 55, label: "Chậu rửa mặt đôi" },
      { id: "hs-5-3", productId: "v_shower_9", x: 20, y: 40, label: "Hệ thống sen tắm âm tường" },
      { id: "hs-5-4", productId: "v_toilet_10", x: 80, y: 65, label: "Bồn cầu NEOREST" },
      { id: "hs-5-5", productId: "v_tile_5", x: 15, y: 80, label: "Gạch khổ lớn cao cấp" }
    ],
    whyItWorks: ["Tinh tế", "Đẳng cấp", "Công nghệ cao"],
    productCount: 7,
    suitableFor: ["Biệt thự", "Căn hộ Duplex"],
    painPoints: ["Cần không gian xứng tầm"],
    keyProducts: ["Bồn tắm độc lập (cần thêm)", "Sen âm tường", "Bồn cầu thông minh"],
    estimatedBudgetMin: 90000000,
    estimatedBudgetMax: 150000000,
    sourceNote: "Ảnh concept minh hoạ"
  },
  {
    id: "vc-bath-6",
    slug: "phong-tam-toi-gian-trang-sang",
    title: "Phòng tắm tối giản trắng sáng",
    roomType: "Phòng tắm",
    style: "Minimal",
    budgetRange: "30–60 triệu",
    areaSize: "4-6m²",
    shortDescription: "Concept demo",
    description: "Phong cách tối giản làm bừng sáng mọi không gian hẹp.",
    longDescription: "Tông màu trắng tinh khôi từ gạch ốp tường đến thiết bị vệ sinh, kết hợp cùng ánh sáng tự nhiên giúp phòng tắm trông sạch sẽ và rộng hơn gấp đôi.",
    image: "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=1080&q=80",
    imageAlt: "Phòng tắm tối giản tông trắng",
    productIds: ["v_lavabo_2", "v_faucet_2", "v_toilet_2", "v_shower_4", "v_mirror_2", "v_tile_1"],
    hotspots: [
      { id: "hs-6-1", productId: "v_mirror_2", x: 52, y: 28, label: "Gương viền mỏng" },
      { id: "hs-6-2", productId: "v_lavabo_2", x: 50, y: 55, label: "Lavabo vuông vắn" },
      { id: "hs-6-3", productId: "v_faucet_2", x: 48, y: 48, label: "Vòi lavabo cong" },
      { id: "hs-6-4", productId: "v_shower_4", x: 22, y: 35, label: "Sen tắm âm tường" },
      { id: "hs-6-5", productId: "v_toilet_2", x: 76, y: 62, label: "Bồn cầu 1 khối" }
    ],
    whyItWorks: ["Rộng rãi", "Sạch sẽ", "Thanh lịch"],
    productCount: 6,
    suitableFor: ["Căn hộ hiện đại", "Người thích sự gọn gàng"],
    painPoints: ["Không gian tối tăm", "Nhiều góc chết"],
    keyProducts: ["Gạch ốp tường trắng", "Thiết bị sứ trắng nguyên khối"],
    estimatedBudgetMin: 25000000,
    estimatedBudgetMax: 40000000,
    sourceNote: "Ảnh concept minh hoạ"
  },
  {
    id: "vc-bath-7",
    slug: "phong-tam-warm-neutral",
    title: "Phòng tắm Warm Neutral",
    roomType: "Phòng tắm",
    style: "Warm Neutral",
    budgetRange: "30–60 triệu",
    areaSize: "5-7m²",
    shortDescription: "Concept demo",
    description: "Tông màu be ấm áp tạo cảm giác an tâm và chữa lành.",
    longDescription: "Sử dụng gạch vân đá tông màu beige, kết hợp với ánh sáng vàng ấm và các thiết bị mạ vàng hồng hoặc xám nhạt để tạo nên một không gian tắm ấm cúng.",
    image: "https://images.unsplash.com/photo-1620626011761-996317702782?w=1080&q=80",
    imageAlt: "Phòng tắm màu be ấm",
    productIds: ["v_lavabo_6", "v_faucet_7", "v_toilet_6", "v_shower_7", "v_mirror_5", "v_tile_3"],
    hotspots: [
      { id: "hs-7-1", productId: "v_mirror_5", x: 50, y: 30, label: "Gương LED tròn" },
      { id: "hs-7-2", productId: "v_lavabo_6", x: 50, y: 55, label: "Lavabo màu nhám" },
      { id: "hs-7-3", productId: "v_shower_7", x: 20, y: 40, label: "Sen tắm màu đồng/xám" },
      { id: "hs-7-4", productId: "v_toilet_6", x: 80, y: 65, label: "Bồn cầu hiện đại" },
      { id: "hs-7-5", productId: "v_tile_3", x: 15, y: 80, label: "Gạch màu be ấm" }
    ],
    whyItWorks: ["Ấm cúng", "Không lỗi mốt", "Dễ chịu"],
    productCount: 6,
    suitableFor: ["Gia đình trẻ", "Nhà phố"],
    painPoints: ["Cảm giác lạnh lẽo của gạch trắng"],
    keyProducts: ["Gạch vân đá màu be", "Sen vòi tông ấm"],
    estimatedBudgetMin: 35000000,
    estimatedBudgetMax: 55000000,
    sourceNote: "Ảnh concept minh hoạ"
  },
  {
    id: "vc-bath-8",
    slug: "phong-tam-den-trang-hien-dai",
    title: "Phòng tắm đen trắng hiện đại",
    roomType: "Phòng tắm",
    style: "Modern",
    budgetRange: "30–60 triệu",
    areaSize: "5-8m²",
    shortDescription: "Concept demo",
    description: "Sự tương phản ấn tượng và mạnh mẽ dành cho phái mạnh.",
    longDescription: "Sử dụng thiết bị sen vòi màu đen mờ (matte black) nổi bật trên nền gạch trắng, mang lại vẻ đẹp cá tính, gọn gàng và đầy nam tính.",
    image: "https://images.unsplash.com/photo-1604147706283-d7119b5b822c?w=1080&q=80",
    imageAlt: "Phòng tắm đen trắng",
    productIds: ["v_lavabo_4", "v_faucet_5", "v_toilet_5", "v_shower_5", "v_mirror_4", "v_tile_4", "v_acc_4"],
    hotspots: [
      { id: "hs-8-1", productId: "v_mirror_4", x: 50, y: 30, label: "Gương viền đen" },
      { id: "hs-8-2", productId: "v_lavabo_4", x: 50, y: 55, label: "Lavabo vuông" },
      { id: "hs-8-3", productId: "v_faucet_5", x: 50, y: 48, label: "Vòi lavabo đen mờ" },
      { id: "hs-8-4", productId: "v_shower_5", x: 20, y: 40, label: "Sen cây đen mờ" },
      { id: "hs-8-5", productId: "v_tile_4", x: 15, y: 80, label: "Gạch xám nhạt/trắng" }
    ],
    whyItWorks: ["Cá tính", "Mạnh mẽ", "Tương phản cao"],
    productCount: 7,
    suitableFor: ["Nam giới độc thân", "Căn hộ Loft"],
    painPoints: ["Thiếu sự phá cách", "Dễ bám vân tay ở đồ mạ bóng"],
    keyProducts: ["Sen vòi đen mờ", "Phụ kiện đen"],
    estimatedBudgetMin: 30000000,
    estimatedBudgetMax: 50000000,
    sourceNote: "Ảnh concept minh hoạ"
  },
  {
    id: "vc-bath-9",
    slug: "phong-tam-chong-am-cho-khi-hau-vn",
    title: "Phòng tắm chống ẩm cho khí hậu Việt Nam",
    roomType: "Phòng tắm",
    style: "Family-friendly",
    budgetRange: "Dưới 30 triệu",
    areaSize: "4-6m²",
    shortDescription: "Concept demo",
    description: "Giải pháp hạn chế nấm mốc và đọng nước hiệu quả.",
    longDescription: "Sử dụng vách kính tắm đứng (shower enclosure) để chia tách không gian khô - ướt rõ ràng, kết hợp quạt hút ẩm và gạch chống trơn, rất phù hợp với khí hậu nồm ẩm tại Việt Nam.",
    image: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=1080&q=80",
    imageAlt: "Phòng tắm chống ẩm",
    productIds: ["v_lavabo_3", "v_faucet_4", "v_toilet_3", "v_shower_3", "v_mirror_3", "v_tile_6"],
    hotspots: [
      { id: "hs-9-1", productId: "v_mirror_3", x: 50, y: 30, label: "Gương sấy nhiệt" },
      { id: "hs-9-2", productId: "v_lavabo_3", x: 50, y: 55, label: "Lavabo chống bám bẩn" },
      { id: "hs-9-3", productId: "v_toilet_3", x: 80, y: 65, label: "Bồn cầu kháng khuẩn" },
      { id: "hs-9-4", productId: "v_tile_6", x: 15, y: 80, label: "Gạch chống trơn" }
    ],
    whyItWorks: ["An toàn", "Khô ráo", "Sạch sẽ"],
    productCount: 6,
    suitableFor: ["Mọi gia đình", "Nhà đất mặt đất"],
    painPoints: ["Sàn ướt nhẹp", "Nấm mốc vào mùa nồm"],
    keyProducts: ["Gạch chống trơn nhám", "Gương có sấy"],
    estimatedBudgetMin: 20000000,
    estimatedBudgetMax: 35000000,
    sourceNote: "Ảnh concept minh hoạ"
  },
  {
    id: "vc-bath-10",
    slug: "phong-tam-de-ve-sinh-gia-dinh-ban-ron",
    title: "Phòng tắm dễ vệ sinh cho gia đình bận rộn",
    roomType: "Phòng tắm",
    style: "Family-friendly",
    budgetRange: "30–60 triệu",
    areaSize: "5-7m²",
    shortDescription: "Concept demo",
    description: "Tối giản các chi tiết góc cạnh để làm sạch nhanh chóng.",
    longDescription: "Bồn cầu treo tường (Wall-hung toilet) giúp giải phóng mặt sàn, chậu lavabo đúc liền khối không có khe hở, giúp việc lau chùi trở nên cực kỳ nhẹ nhàng và nhanh chóng.",
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=1080&q=80",
    imageAlt: "Phòng tắm dễ vệ sinh",
    productIds: ["v_lavabo_9", "v_faucet_8", "v_toilet_9", "v_shower_8", "v_mirror_6", "v_cabinet_3"],
    hotspots: [
      { id: "hs-10-1", productId: "v_lavabo_9", x: 50, y: 55, label: "Lavabo nguyên khối" },
      { id: "hs-10-2", productId: "v_toilet_9", x: 80, y: 60, label: "Bồn cầu treo tường" },
      { id: "hs-10-3", productId: "v_cabinet_3", x: 50, y: 70, label: "Tủ lavabo treo" }
    ],
    whyItWorks: ["Tiết kiệm thời gian", "Không góc chết"],
    productCount: 6,
    suitableFor: ["Gia đình bận rộn"],
    painPoints: ["Cọ rửa mệt mỏi", "Bụi bẩn bám kẽ"],
    keyProducts: ["Bồn cầu treo tường", "Lavabo đúc liền"],
    estimatedBudgetMin: 40000000,
    estimatedBudgetMax: 60000000,
    sourceNote: "Ảnh concept minh hoạ"
  },
  {
    id: "vc-bath-11",
    slug: "phong-tam-homestay-boutique",
    title: "Phòng tắm cho homestay phong cách boutique",
    roomType: "Phòng tắm",
    style: "Boutique",
    budgetRange: "Dưới 30 triệu",
    areaSize: "4-6m²",
    shortDescription: "Concept demo",
    description: "Đẹp mắt, lên hình ấn tượng nhưng chi phí hợp lý.",
    longDescription: "Sử dụng điểm nhấn như gương LED kiểu dáng lạ mắt, vòi lavabo màu vàng gold hoặc mạ đồng, và gạch thẻ trang trí (subway tile) tạo nên góc check-in tuyệt vời cho khách hàng.",
    image: "https://images.unsplash.com/photo-1620626011761-996317702782?w=1080&q=80",
    imageAlt: "Phòng tắm boutique",
    productIds: ["v_lavabo_6", "v_faucet_7", "v_toilet_4", "v_shower_7", "v_mirror_5", "v_acc_5"],
    hotspots: [
      { id: "hs-11-1", productId: "v_mirror_5", x: 50, y: 30, label: "Gương LED trang trí" },
      { id: "hs-11-2", productId: "v_faucet_7", x: 50, y: 48, label: "Vòi mạ đồng/vàng" }
    ],
    whyItWorks: ["Ăn ảnh", "Độc đáo", "Thu hút khách"],
    productCount: 6,
    suitableFor: ["Homestay", "Boutique Hotel"],
    painPoints: ["Phòng tắm quá nhàm chán", "Không có góc chụp hình"],
    keyProducts: ["Gương LED hình thù lạ", "Phụ kiện mạ vàng"],
    estimatedBudgetMin: 15000000,
    estimatedBudgetMax: 28000000,
    sourceNote: "Ảnh concept minh hoạ"
  },
  {
    id: "vc-bath-12",
    slug: "phong-tam-compact-co-tu",
    title: "Phòng tắm compact có tủ lavabo",
    roomType: "Phòng tắm",
    style: "Compact",
    budgetRange: "Dưới 30 triệu",
    areaSize: "3-5m²",
    shortDescription: "Concept demo",
    description: "Gọn gàng tối đa với tủ chậu thông minh.",
    longDescription: "Giải quyết bài toán phòng tắm nhỏ nhiều đồ đạc bằng một hệ tủ lavabo nhựa PVC chống nước gọn nhẹ, giấu đi đường ống và cung cấp đủ không gian chứa chai lọ gội xả.",
    image: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=1080&q=80",
    imageAlt: "Phòng tắm compact với tủ",
    productIds: ["v_lavabo_5", "v_faucet_2", "v_toilet_2", "v_shower_2", "v_mirror_2", "v_cabinet_1"],
    hotspots: [
      { id: "hs-12-1", productId: "v_cabinet_1", x: 50, y: 70, label: "Tủ nhựa PVC chống nước" },
      { id: "hs-12-2", productId: "v_lavabo_5", x: 50, y: 55, label: "Lavabo âm bàn" }
    ],
    whyItWorks: ["Gọn gàng", "Chứa nhiều đồ", "Giá hợp lý"],
    productCount: 6,
    suitableFor: ["Căn hộ nhỏ", "Gia đình nhiều đồ dùng"],
    painPoints: ["Bừa bộn chai lọ trên bồn rửa"],
    keyProducts: ["Tủ chậu PVC liền khối"],
    estimatedBudgetMin: 15000000,
    estimatedBudgetMax: 25000000,
    sourceNote: "Ảnh concept minh hoạ"
  },
  {
    id: "vc-bath-13",
    slug: "phong-tam-cho-nha-pho-hep",
    title: "Phòng tắm cho nhà phố hẹp",
    roomType: "Phòng tắm",
    style: "Minimal",
    budgetRange: "Dưới 30 triệu",
    areaSize: "2.5-4m²",
    shortDescription: "Concept demo",
    description: "Thiết kế hẹp bề ngang nhưng dài sâu cho nhà ống.",
    longDescription: "Bố trí thiết bị dọc theo một bên tường để tiết kiệm tối đa lối đi, sử dụng cửa kính trượt để ngăn khu vực tắm mà không chiếm diện tích mở cửa.",
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=1080&q=80",
    imageAlt: "Phòng tắm nhà ống hẹp",
    productIds: ["v_lavabo_1", "v_faucet_3", "v_toilet_2", "v_shower_3", "v_mirror_1", "v_acc_2"],
    hotspots: [
      { id: "hs-13-1", productId: "v_lavabo_1", x: 50, y: 55, label: "Lavabo góc/treo nhỏ" },
      { id: "hs-13-2", productId: "v_toilet_2", x: 80, y: 65, label: "Bồn cầu gọn gàng" }
    ],
    whyItWorks: ["Tối ưu bề ngang", "Di chuyển dễ dàng"],
    productCount: 6,
    suitableFor: ["Nhà ống", "Nhà phố diện tích nhỏ"],
    painPoints: ["Không gian hẹp và dài khó bố trí"],
    keyProducts: ["Lavabo nhỏ gọn", "Sen tắm vách kính trượt"],
    estimatedBudgetMin: 12000000,
    estimatedBudgetMax: 22000000,
    sourceNote: "Ảnh concept minh hoạ"
  },
  {
    id: "vc-bath-14",
    slug: "phong-tam-sang-mau-cai-tao-cu",
    title: "Phòng tắm sáng màu cho căn hộ cũ",
    roomType: "Phòng tắm",
    style: "Modern",
    budgetRange: "30–60 triệu",
    areaSize: "4-6m²",
    shortDescription: "Concept demo",
    description: "Lột xác phòng tắm cũ kỹ trở nên hiện đại, sáng sủa.",
    longDescription: "Cải tạo toàn diện bằng gạch ốp sáng màu, thiết bị vệ sinh mạ chrome bóng loáng giúp phản chiếu ánh sáng tốt hơn, xoá bỏ hoàn toàn cảm giác cũ kỹ.",
    image: "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=1080&q=80",
    imageAlt: "Cải tạo phòng tắm sáng màu",
    productIds: ["v_lavabo_10", "v_faucet_2", "v_toilet_3", "v_shower_2", "v_mirror_2", "v_cabinet_2"],
    hotspots: [
      { id: "hs-14-1", productId: "v_lavabo_10", x: 50, y: 55, label: "Lavabo mới sáng bóng" },
      { id: "hs-14-2", productId: "v_mirror_2", x: 50, y: 30, label: "Gương to bản" }
    ],
    whyItWorks: ["Tươi mới", "Cải thiện ánh sáng", "Sạch sẽ"],
    productCount: 6,
    suitableFor: ["Dự án cải tạo nhà"],
    painPoints: ["Phòng tắm cũ kỹ ố vàng", "Thiếu ánh sáng"],
    keyProducts: ["Sứ vệ sinh men chống bám bẩn", "Gương bản lớn"],
    estimatedBudgetMin: 28000000,
    estimatedBudgetMax: 45000000,
    sourceNote: "Ảnh concept minh hoạ"
  },
  {
    id: "vc-bath-15",
    slug: "phong-tam-luxury-sen-cay-guong-led",
    title: "Phòng tắm luxury với sen cây và gương LED",
    roomType: "Phòng tắm",
    style: "Luxury",
    budgetRange: "Trên 60 triệu",
    areaSize: "6-8m²",
    shortDescription: "Concept demo",
    description: "Trải nghiệm tắm thư giãn tột bậc với công nghệ hiện đại.",
    longDescription: "Điểm nhấn là sen cây nhiệt độ chống phỏng cao cấp và gương LED cảm ứng có chức năng sấy khô chống mờ sương, kết hợp với các chi tiết kim loại sang trọng.",
    image: "https://images.unsplash.com/photo-1507652313656-b14ef9c5f4ba?w=1080&q=80",
    imageAlt: "Phòng tắm Luxury công nghệ",
    productIds: ["v_lavabo_8", "v_faucet_9", "v_toilet_8", "v_shower_8", "v_mirror_8", "v_cabinet_5", "v_acc_8"],
    hotspots: [
      { id: "hs-15-1", productId: "v_shower_8", x: 20, y: 40, label: "Sen cây tĩnh nhiệt" },
      { id: "hs-15-2", productId: "v_mirror_8", x: 50, y: 30, label: "Gương LED chống sương" },
      { id: "hs-15-3", productId: "v_toilet_8", x: 80, y: 65, label: "Bồn cầu điện tử" }
    ],
    whyItWorks: ["Hiện đại", "Tiện nghi cao cấp", "Thư giãn"],
    productCount: 7,
    suitableFor: ["Người yêu công nghệ", "Căn hộ cao cấp"],
    painPoints: ["Cần nâng cấp trải nghiệm sống"],
    keyProducts: ["Sen tĩnh nhiệt", "Gương sấy chống mờ"],
    estimatedBudgetMin: 70000000,
    estimatedBudgetMax: 110000000,
    sourceNote: "Ảnh concept minh hoạ"
  },
  {
    id: "vc-bath-16",
    slug: "phong-tam-budget-duoi-20-trieu",
    title: "Phòng tắm budget dưới 20 triệu",
    roomType: "Phòng tắm",
    style: "Budget",
    budgetRange: "Dưới 20 triệu",
    areaSize: "3-5m²",
    shortDescription: "Concept demo",
    description: "Chỉ với ngân sách thấp nhưng vẫn trọn bộ tiện nghi chính hãng.",
    longDescription: "Sử dụng các sản phẩm cơ bản nhưng chất lượng được bảo chứng từ các hãng lớn, đảm bảo không gặp rắc rối rò rỉ nước hay bong tróc sau thời gian ngắn sử dụng.",
    image: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=1080&q=80",
    imageAlt: "Phòng tắm tiết kiệm",
    productIds: ["v_lavabo_1", "v_faucet_1", "v_toilet_1", "v_shower_1", "v_mirror_1", "v_acc_1"],
    hotspots: [
      { id: "hs-16-1", productId: "v_lavabo_1", x: 50, y: 55, label: "Lavabo cơ bản" },
      { id: "hs-16-2", productId: "v_toilet_1", x: 80, y: 65, label: "Bồn cầu tiết kiệm" }
    ],
    whyItWorks: ["Rẻ", "Đảm bảo chất lượng", "Chính hãng"],
    productCount: 6,
    suitableFor: ["Ngân sách cực hạn chế", "Xây nhà trọ"],
    painPoints: ["Sợ mua nhầm hàng giả giá rẻ nhanh hỏng"],
    keyProducts: ["Combo thiết bị cơ bản thương hiệu uy tín"],
    estimatedBudgetMin: 6000000,
    estimatedBudgetMax: 15000000,
    sourceNote: "Ảnh concept minh hoạ"
  },
  {
    id: "vc-bath-17",
    slug: "phong-tam-can-bang-30-60-trieu",
    title: "Phòng tắm cân bằng 30-60 triệu",
    roomType: "Phòng tắm",
    style: "Modern",
    budgetRange: "30–60 triệu",
    areaSize: "4-7m²",
    shortDescription: "Concept demo",
    description: "Lựa chọn phổ biến nhất cho các gia đình hiện đại.",
    longDescription: "Mức ngân sách tối ưu để sở hữu đầy đủ thiết bị từ tủ chậu lavabo, vách tắm kính, sen cây đến bồn cầu 1 khối thiết kế đẹp, bền bỉ và dễ vệ sinh.",
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=1080&q=80",
    imageAlt: "Phòng tắm cân bằng",
    productIds: ["v_lavabo_5", "v_faucet_4", "v_toilet_4", "v_shower_4", "v_mirror_3", "v_cabinet_2"],
    hotspots: [
      { id: "hs-17-1", productId: "v_toilet_4", x: 80, y: 65, label: "Bồn cầu 1 khối" },
      { id: "hs-17-2", productId: "v_cabinet_2", x: 50, y: 70, label: "Tủ chậu chống nước" },
      { id: "hs-17-3", productId: "v_shower_4", x: 20, y: 40, label: "Sen cây thẩm mỹ" }
    ],
    whyItWorks: ["Chất lượng cao", "Thẩm mỹ tốt", "Đáng tiền"],
    productCount: 6,
    suitableFor: ["Đa số các gia đình", "Chung cư"],
    painPoints: ["Phân vân giữa giá rẻ và quá đắt"],
    keyProducts: ["Bồn cầu 1 khối", "Tủ chậu tiện ích"],
    estimatedBudgetMin: 30000000,
    estimatedBudgetMax: 50000000,
    sourceNote: "Ảnh concept minh hoạ"
  },
  {
    id: "vc-bath-18",
    slug: "phong-tam-cao-cap-tren-60-trieu",
    title: "Phòng tắm cao cấp trên 60 triệu",
    roomType: "Phòng tắm",
    style: "Luxury",
    budgetRange: "Trên 60 triệu",
    areaSize: "6-12m²",
    shortDescription: "Concept demo",
    description: "Sự kết hợp của các thiết kế đoạt giải thưởng và vật liệu hạng sang.",
    longDescription: "Dành cho những gia chủ đòi hỏi khắt khe nhất về thiết kế. Thiết bị vệ sinh không chỉ để sử dụng mà là các tác phẩm nghệ thuật tô điểm cho không gian sống.",
    image: "https://images.unsplash.com/photo-1595514535315-2a25598816cb?w=1080&q=80",
    imageAlt: "Phòng tắm siêu cao cấp",
    productIds: ["v_lavabo_11", "v_faucet_10", "v_toilet_10", "v_shower_10", "v_mirror_8", "v_cabinet_6"],
    hotspots: [
      { id: "hs-18-1", productId: "v_toilet_10", x: 80, y: 65, label: "Bồn cầu thông minh tự động" },
      { id: "hs-18-2", productId: "v_faucet_10", x: 50, y: 48, label: "Vòi lavabo thiết kế Ý" },
      { id: "hs-18-3", productId: "v_shower_10", x: 20, y: 40, label: "Sen tắm âm trần đa chế độ" }
    ],
    whyItWorks: ["Độc bản", "Siêu tiện nghi", "Công nghệ tiên phong"],
    productCount: 6,
    suitableFor: ["Giới tinh hoa", "Thiết kế riêng"],
    painPoints: ["Cần khẳng định đẳng cấp cá nhân"],
    keyProducts: ["Thiết bị mạ vàng/đen mờ đặc biệt", "Sen âm trần"],
    estimatedBudgetMin: 80000000,
    estimatedBudgetMax: 200000000,
    sourceNote: "Ảnh concept minh hoạ"
  },

  // B. KITCHEN CONCEPTS (5 concepts)
  {
    id: "vc-kit-1",
    slug: "goc-bep-can-ho-toi-gian",
    title: "Góc bếp căn hộ tối giản",
    roomType: "Bếp",
    style: "Minimal",
    budgetRange: "Linh hoạt theo báo giá",
    areaSize: "6-10m²",
    shortDescription: "Concept demo",
    description: "Bếp gọn gàng, giấu đồ thông minh giúp không gian chung cư rộng rãi hơn.",
    longDescription: "Thiết kế phẳng, không tay nắm kết hợp với các vòi rửa bát hiện đại, chậu rửa bát inox 304 đúc liền chống bám bẩn.",
    image: "https://images.unsplash.com/photo-1556909211-36987dafdd4b?w=1080&q=80",
    imageAlt: "Bếp tối giản",
    productIds: ["v_faucet_2"], // Kitchen catalogue is limited, reuse valid products and fallback
    hotspots: [
      { id: "hs-k1-1", productId: "v_faucet_2", x: 50, y: 55, label: "Vòi rửa cổ ngỗng cong" }
    ],
    whyItWorks: ["Sạch sẽ", "Gọn gàng", "Dễ lau chùi"],
    productCount: 1,
    suitableFor: ["Căn hộ", "Chung cư"],
    painPoints: ["Bếp bừa bộn", "Không có nơi để đồ"],
    keyProducts: ["Vòi rửa chén", "Chậu rửa inox 304"],
    estimatedBudgetMin: 30000000,
    estimatedBudgetMax: 70000000,
    sourceNote: "Concept bếp hiện tại dùng dữ liệu mẫu hạn chế, sẽ bổ sung catalogue chuyên bếp sau."
  },
  {
    id: "vc-kit-2",
    slug: "bep-chu-i-cho-can-ho-nho",
    title: "Bếp chữ I cho căn hộ nhỏ",
    roomType: "Bếp",
    style: "Compact",
    budgetRange: "Dưới 30 triệu",
    areaSize: "3-5m²",
    shortDescription: "Concept demo",
    description: "Tiết kiệm tối đa diện tích dọc theo hành lang căn hộ.",
    longDescription: "Bố trí bồn rửa, khu sơ chế và bếp từ trên cùng một đường thẳng. Rất phù hợp cho các căn hộ studio hoặc căn 1PN nhỏ.",
    image: "https://images.unsplash.com/photo-1556910103-1c02745a872f?w=1080&q=80",
    imageAlt: "Bếp chữ I nhỏ gọn",
    productIds: ["v_faucet_1", "v_tile_1"],
    hotspots: [
      { id: "hs-k2-1", productId: "v_faucet_1", x: 60, y: 50, label: "Vòi bồn rửa" },
      { id: "hs-k2-2", productId: "v_tile_1", x: 40, y: 30, label: "Gạch ốp bếp dễ lau" }
    ],
    whyItWorks: ["Tối ưu diện tích", "Tiết kiệm chi phí"],
    productCount: 2,
    suitableFor: ["Căn hộ nhỏ", "Studio"],
    painPoints: ["Thiếu không gian mặt bếp"],
    keyProducts: ["Phụ kiện thông minh", "Vòi rửa gọn"],
    estimatedBudgetMin: 20000000,
    estimatedBudgetMax: 35000000,
    sourceNote: "Concept bếp hiện tại dùng dữ liệu mẫu."
  },
  {
    id: "vc-kit-3",
    slug: "bep-warm-neutral-gia-dinh",
    title: "Bếp Warm Neutral cho gia đình trẻ",
    roomType: "Bếp",
    style: "Warm Neutral",
    budgetRange: "30–60 triệu",
    areaSize: "8-12m²",
    shortDescription: "Concept demo",
    description: "Tông màu kem ấm áp là nơi gia đình quây quần mỗi tối.",
    longDescription: "Sử dụng vật liệu bề mặt mờ nhám chống vân tay màu trà sữa hoặc be ấm, kết hợp với ánh sáng vàng tạo cảm giác sum vầy.",
    image: "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=1080&q=80",
    imageAlt: "Bếp Warm Neutral gia đình",
    productIds: ["v_faucet_7", "v_tile_3"],
    hotspots: [
      { id: "hs-k3-1", productId: "v_faucet_7", x: 50, y: 55, label: "Vòi mạ màu đồng/vàng ấm" },
      { id: "hs-k3-2", productId: "v_tile_3", x: 20, y: 60, label: "Sàn giả gỗ hoặc vân đá be" }
    ],
    whyItWorks: ["Ấm cúng", "Sang trọng", "Gần gũi"],
    productCount: 2,
    suitableFor: ["Gia đình", "Chung cư trung cấp"],
    painPoints: ["Bếp màu trắng quá lạnh lẽo"],
    keyProducts: ["Vòi nước màu ấm", "Sàn chống trơn"],
    estimatedBudgetMin: 40000000,
    estimatedBudgetMax: 80000000,
    sourceNote: "Concept bếp hiện tại dùng dữ liệu mẫu."
  },
  {
    id: "vc-kit-4",
    slug: "bep-rental-de-bao-tri",
    title: "Bếp rental dễ bảo trì",
    roomType: "Bếp",
    style: "Budget",
    budgetRange: "Dưới 30 triệu",
    areaSize: "5-8m²",
    shortDescription: "Concept demo",
    description: "Vật liệu siêu bền, giá thành hợp lý, đầu tư hiệu quả.",
    longDescription: "Thiết kế sử dụng tủ bếp nhựa lõi đặc hoặc inox siêu bền, chống mối mọt cong vênh tuyệt đối, phục vụ mục đích cho thuê lâu dài không phải sửa chữa.",
    image: "https://images.unsplash.com/photo-1556912173-3bb406ef7e77?w=1080&q=80",
    imageAlt: "Bếp cho thuê dễ bảo trì",
    productIds: ["v_faucet_3", "v_tile_6"],
    hotspots: [
      { id: "hs-k4-1", productId: "v_faucet_3", x: 45, y: 55, label: "Vòi rửa bát cơ bản bền bỉ" }
    ],
    whyItWorks: ["Bền", "Rẻ", "Dễ làm sạch"],
    productCount: 2,
    suitableFor: ["Nhà cho thuê", "Phòng trọ"],
    painPoints: ["Tủ bếp gỗ công nghiệp bị ngấm nước, mối mọt"],
    keyProducts: ["Bồn rửa inox 304", "Vòi lạnh đơn giản"],
    estimatedBudgetMin: 15000000,
    estimatedBudgetMax: 25000000,
    sourceNote: "Concept bếp hiện tại dùng dữ liệu mẫu."
  },
  {
    id: "vc-kit-5",
    slug: "bep-japandi-sang-mau",
    title: "Bếp Japandi sáng màu",
    roomType: "Bếp",
    style: "Japandi",
    budgetRange: "30–60 triệu",
    areaSize: "10-15m²",
    shortDescription: "Concept demo",
    description: "Sự thanh lịch từ gỗ sáng màu và những đường nét bo tròn.",
    longDescription: "Tạo một không gian thiền định ngay trong bếp với tông màu gỗ sồi tự nhiên, mặt bàn đá thạch anh trắng và các chậu rửa bằng đá granit hoặc sứ cao cấp.",
    image: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=1080&q=80",
    imageAlt: "Bếp Japandi vân gỗ",
    productIds: ["v_faucet_6", "v_tile_3"],
    hotspots: [
      { id: "hs-k5-1", productId: "v_faucet_6", x: 50, y: 50, label: "Vòi nước màu đen/inox xước" }
    ],
    whyItWorks: ["Nhẹ nhàng", "Gần gũi thiên nhiên", "Yên bình"],
    productCount: 2,
    suitableFor: ["Người yêu thích sự tinh giản"],
    painPoints: ["Không gian ngột ngạt", "Thiếu ánh sáng"],
    keyProducts: ["Mặt đá thạch anh", "Tủ vân sồi"],
    estimatedBudgetMin: 50000000,
    estimatedBudgetMax: 90000000,
    sourceNote: "Concept bếp hiện tại dùng dữ liệu mẫu."
  },

  // C. LIVING ROOM CONCEPTS (6 concepts)
  {
    id: "vc-liv-1",
    slug: "phong-khach-toi-gian-am",
    title: "Phòng khách tối giản ấm",
    roomType: "Phòng khách",
    style: "Minimal",
    budgetRange: "30–60 triệu",
    areaSize: "15-20m²",
    shortDescription: "Concept demo",
    description: "Giảm bớt đồ đạc, tăng thêm ánh sáng và chất cảm vật liệu.",
    longDescription: "Không gian tiếp khách không còn cồng kềnh tủ kệ mà thay vào đó là bộ sofa vải êm ái, ánh sáng dịu nhẹ và mảng tường điểm nhấn bằng gạch khổ lớn vân đá mờ.",
    image: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=1080&q=80",
    imageAlt: "Phòng khách tối giản ấm",
    productIds: ["v_tile_2"], // Use tiles/lights if available
    hotspots: [
      { id: "hs-l1-1", productId: "v_tile_2", x: 20, y: 70, label: "Sàn gạch khổ lớn/Gỗ" }
    ],
    whyItWorks: ["Rộng rãi", "Dễ chịu", "Ít bám bụi"],
    productCount: 1,
    suitableFor: ["Chung cư", "Nhà phố"],
    painPoints: ["Quá nhiều đồ đạc bừa bộn"],
    keyProducts: ["Sofa vải linen", "Sàn vân gỗ/đá mờ"],
    estimatedBudgetMin: 30000000,
    estimatedBudgetMax: 50000000,
    sourceNote: "Sử dụng dữ liệu catalogue tham khảo"
  },
  {
    id: "vc-liv-2",
    slug: "phong-khach-can-ho-nho-sofa-compact",
    title: "Phòng khách căn hộ nhỏ với sofa compact",
    roomType: "Phòng khách",
    style: "Compact",
    budgetRange: "Dưới 30 triệu",
    areaSize: "10-15m²",
    shortDescription: "Concept demo",
    description: "Khéo léo bố trí khu vực sinh hoạt chung trong không gian khiêm tốn.",
    longDescription: "Sử dụng sofa dạng văng (2-3 chỗ ngồi) kết hợp với bàn trà tròn gọn gàng, tạo lối đi thông thoáng cho toàn bộ căn hộ.",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1080&q=80",
    imageAlt: "Phòng khách diện tích nhỏ",
    productIds: ["v_tile_1"],
    hotspots: [
      { id: "hs-l2-1", productId: "v_tile_1", x: 50, y: 80, label: "Sàn sáng màu giúp rộng nhà" }
    ],
    whyItWorks: ["Gọn gàng", "Thông thoáng"],
    productCount: 1,
    suitableFor: ["Căn hộ nhỏ", "Studio"],
    painPoints: ["Lối đi chật hẹp do sofa quá to"],
    keyProducts: ["Sofa compact", "Bàn trà nhỏ"],
    estimatedBudgetMin: 15000000,
    estimatedBudgetMax: 25000000,
    sourceNote: "Sử dụng dữ liệu catalogue tham khảo"
  },
  {
    id: "vc-liv-3",
    slug: "phong-khach-japandi",
    title: "Phòng khách Japandi",
    roomType: "Phòng khách",
    style: "Japandi",
    budgetRange: "30–60 triệu",
    areaSize: "15-25m²",
    shortDescription: "Concept demo",
    description: "Sự tĩnh lặng của mây tre, gỗ sồi và đồ nội thất dáng thấp.",
    longDescription: "Tạo không gian thiền thư giãn ở ngay phòng khách với sofa dáng bệt, rèm vải voan mỏng và các đồ trang trí bằng thủ công mỹ nghệ nhẹ nhàng.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1080&q=80",
    imageAlt: "Phòng khách Japandi mộc mạc",
    productIds: ["v_tile_3"],
    hotspots: [
      { id: "hs-l3-1", productId: "v_tile_3", x: 50, y: 80, label: "Sàn vân gỗ sáng" }
    ],
    whyItWorks: ["Thư giãn tâm trí", "Cảm giác bình yên"],
    productCount: 1,
    suitableFor: ["Căn hộ Japandi", "Nhà phong cách Nhật"],
    painPoints: ["Không gian thiếu tính nghỉ ngơi"],
    keyProducts: ["Sofa bệt", "Rèm voan", "Sàn gỗ sáng"],
    estimatedBudgetMin: 35000000,
    estimatedBudgetMax: 60000000,
    sourceNote: "Sử dụng dữ liệu catalogue tham khảo"
  },
  {
    id: "vc-liv-4",
    slug: "phong-khach-warm-neutral",
    title: "Phòng khách Warm Neutral",
    roomType: "Phòng khách",
    style: "Warm Neutral",
    budgetRange: "30–60 triệu",
    areaSize: "20-30m²",
    shortDescription: "Concept demo",
    description: "Thanh lịch vượt thời gian với các dải màu từ kem đến nâu nhạt.",
    longDescription: "Tone màu beige chủ đạo ở sofa, thảm, rèm kết hợp với ánh sáng đèn màu ấm (3000K) biến phòng khách thành không gian lý tưởng nhất cho buổi tối gia đình.",
    image: "https://images.unsplash.com/photo-1593696140826-c58b021acf8b?w=1080&q=80",
    imageAlt: "Phòng khách ấm áp màu be",
    productIds: ["v_tile_3"],
    hotspots: [
      { id: "hs-l4-1", productId: "v_tile_3", x: 40, y: 80, label: "Sàn tông ấm" }
    ],
    whyItWorks: ["Sang trọng mềm mại", "Không bao giờ lỗi thời"],
    productCount: 1,
    suitableFor: ["Biệt thự", "Chung cư diện tích lớn"],
    painPoints: ["Nhà quá lạnh vì chỉ sơn màu trắng sứ"],
    keyProducts: ["Sofa nhung tăm/lông cừu màu be", "Thảm lớn"],
    estimatedBudgetMin: 40000000,
    estimatedBudgetMax: 80000000,
    sourceNote: "Sử dụng dữ liệu catalogue tham khảo"
  },
  {
    id: "vc-liv-5",
    slug: "phong-khach-homestay",
    title: "Phòng khách cho homestay",
    roomType: "Phòng khách",
    style: "Boutique",
    budgetRange: "Dưới 30 triệu",
    areaSize: "12-20m²",
    shortDescription: "Concept demo",
    description: "Trẻ trung, phá cách và cực kỳ ăn ảnh.",
    longDescription: "Sử dụng sofa màu sắc rực rỡ như cam hoặc xanh cổ vịt làm điểm nhấn, kết hợp tranh treo tường nghệ thuật để khách thuê có góc chụp ảnh kỷ niệm ngay khi bước vào.",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1080&q=80",
    imageAlt: "Phòng khách homestay bắt mắt",
    productIds: ["v_acc_4"],
    hotspots: [
      { id: "hs-l5-1", productId: "v_acc_4", x: 50, y: 50, label: "Phụ kiện trang trí điểm nhấn" }
    ],
    whyItWorks: ["Ấn tượng từ cái nhìn đầu tiên", "Chi phí vừa phải"],
    productCount: 1,
    suitableFor: ["Homestay kinh doanh Airbnb"],
    painPoints: ["Quá an toàn nên không hút khách booking"],
    keyProducts: ["Sofa màu nổi", "Tranh canvas"],
    estimatedBudgetMin: 15000000,
    estimatedBudgetMax: 25000000,
    sourceNote: "Sử dụng dữ liệu catalogue tham khảo"
  },
  {
    id: "vc-liv-6",
    slug: "phong-khach-hien-dai-ngan-sach-vua",
    title: "Phòng khách hiện đại ngân sách vừa",
    roomType: "Phòng khách",
    style: "Modern",
    budgetRange: "Dưới 30 triệu",
    areaSize: "15-20m²",
    shortDescription: "Concept demo",
    description: "Giải pháp an toàn, bền bỉ và hiện đại cho tổ ấm đầu tiên.",
    longDescription: "Lựa chọn các combo nội thất đóng sẵn (ready-to-assemble) hiện đại, chất liệu ván công nghiệp MDF chống ẩm với bề mặt phủ Melamine dễ lau chùi.",
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=1080&q=80",
    imageAlt: "Phòng khách cơ bản hiện đại",
    productIds: ["v_tile_6"],
    hotspots: [
      { id: "hs-l6-1", productId: "v_tile_6", x: 50, y: 80, label: "Sàn gạch/nhựa giả gỗ tiết kiệm" }
    ],
    whyItWorks: ["Giá cả phải chăng", "Dễ thi công", "Nhanh gọn"],
    productCount: 1,
    suitableFor: ["Vợ chồng trẻ mới cưới", "Chung cư tầm trung"],
    painPoints: ["Chi phí làm nội thất gỗ tự nhiên quá cao"],
    keyProducts: ["Kệ tivi MDF", "Sofa nỉ"],
    estimatedBudgetMin: 15000000,
    estimatedBudgetMax: 30000000,
    sourceNote: "Sử dụng dữ liệu catalogue tham khảo"
  },

  // D. STUDIO / RENTAL / HOMESTAY CONCEPTS (5 concepts)
  {
    id: "vc-stu-1",
    slug: "studio-cho-thue-25m2",
    title: "Studio cho thuê 25m²",
    roomType: "Studio",
    style: "Compact",
    budgetRange: "Dưới 30 triệu",
    areaSize: "20-25m²",
    shortDescription: "Concept demo",
    description: "Tối giản đa năng, không gian mở cho người trẻ độc thân.",
    longDescription: "Bố trí giường, bếp, và góc tiếp khách trên cùng một mặt bằng, dùng thảm và ánh sáng để phân chia vùng ảo thay vì xây tường.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1080&q=80",
    imageAlt: "Căn hộ Studio nhỏ",
    productIds: ["v_faucet_3", "v_lavabo_1", "v_shower_1"],
    hotspots: [
      { id: "hs-s1-1", productId: "v_lavabo_1", x: 20, y: 50, label: "Lavabo tích hợp khu vệ sinh gọn" },
      { id: "hs-s1-2", productId: "v_faucet_3", x: 80, y: 50, label: "Bếp nhỏ xinh" }
    ],
    whyItWorks: ["Không vướng víu", "Cảm giác rộng hơn diện tích thực"],
    productCount: 3,
    suitableFor: ["Căn hộ Studio", "Cho thuê sinh viên/người đi làm"],
    painPoints: ["Diện tích quá nhỏ để chia phòng"],
    keyProducts: ["Giường thông minh có ngăn kéo", "Bếp chữ I gọn"],
    estimatedBudgetMin: 20000000,
    estimatedBudgetMax: 40000000,
    sourceNote: "Sử dụng dữ liệu catalogue tham khảo"
  },
  {
    id: "vc-stu-2",
    slug: "studio-japandi-tiet-kiem",
    title: "Studio Japandi tiết kiệm",
    roomType: "Studio",
    style: "Japandi",
    budgetRange: "Dưới 30 triệu",
    areaSize: "25-30m²",
    shortDescription: "Concept demo",
    description: "Chill mọi góc với phong cách tối giản mộc mạc.",
    longDescription: "Sử dụng pallet gỗ tái chế làm giường, rèm sáo tre và chậu cây xanh để tạo không gian check-in như quán cafe ngay trong phòng ở.",
    image: "https://images.unsplash.com/photo-1502672260266-1c1e5250b281?w=1080&q=80",
    imageAlt: "Studio Japandi",
    productIds: ["v_tile_3", "v_mirror_5"],
    hotspots: [
      { id: "hs-s2-1", productId: "v_tile_3", x: 50, y: 80, label: "Sàn vân gỗ ấm áp" },
      { id: "hs-s2-2", productId: "v_mirror_5", x: 80, y: 40, label: "Gương tròn soi toàn thân" }
    ],
    whyItWorks: ["Chill", "Trẻ trung", "Giá cực rẻ do dùng đồ tái chế/lắp ráp"],
    productCount: 2,
    suitableFor: ["Giới trẻ gen Z", "Freelancer"],
    painPoints: ["Sống trong hộp kín nhàm chán"],
    keyProducts: ["Giường pallet", "Gương toàn thân"],
    estimatedBudgetMin: 15000000,
    estimatedBudgetMax: 25000000,
    sourceNote: "Sử dụng dữ liệu catalogue tham khảo"
  },
  {
    id: "vc-stu-3",
    slug: "homestay-mini-phong-cach-khach-san",
    title: "Homestay mini phong cách khách sạn",
    roomType: "Homestay",
    style: "Hotel",
    budgetRange: "30–60 triệu",
    areaSize: "30-40m²",
    shortDescription: "Concept demo",
    description: "Đầu tư trải nghiệm cao cấp để nâng giá booking phòng.",
    longDescription: "Đem hệ thống giường lò xo túi cao cấp, nệm drap trắng chuẩn 5 sao và phòng tắm vách kính trong suốt vào homestay để mang lại trải nghiệm luxury cho cặp đôi.",
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1080&q=80",
    imageAlt: "Homestay chuẩn khách sạn",
    productIds: ["v_lavabo_8", "v_shower_8", "v_mirror_7", "v_tile_5"],
    hotspots: [
      { id: "hs-s3-1", productId: "v_shower_8", x: 80, y: 50, label: "Vách kính tắm sen cây" },
      { id: "hs-s3-2", productId: "v_mirror_7", x: 85, y: 35, label: "Gương LED nịnh mặt" }
    ],
    whyItWorks: ["Trải nghiệm cao", "Khách hàng sẵn sàng chi tiền"],
    productCount: 4,
    suitableFor: ["Homestay cao cấp cho cặp đôi"],
    painPoints: ["Cạnh tranh gay gắt về giá ở phân khúc thấp"],
    keyProducts: ["Drap giường khách sạn", "Sen cây nhiệt độ"],
    estimatedBudgetMin: 45000000,
    estimatedBudgetMax: 70000000,
    sourceNote: "Sử dụng dữ liệu catalogue tham khảo"
  },
  {
    id: "vc-stu-4",
    slug: "can-ho-dich-vu-de-bao-tri",
    title: "Căn hộ dịch vụ dễ bảo trì",
    roomType: "Studio",
    style: "Budget",
    budgetRange: "Dưới 30 triệu",
    areaSize: "30-45m²",
    shortDescription: "Concept demo",
    description: "Bền bỉ, an toàn và dễ dàng dọn dẹp vệ sinh cho quản lý.",
    longDescription: "Toàn bộ sàn lát gạch giả gỗ chống xước chống nước 100%, nội thất phủ Melamine lõi chống ẩm, tường sơn bóng lau chùi được.",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1080&q=80",
    imageAlt: "Căn hộ dịch vụ thực dụng",
    productIds: ["v_tile_6", "v_toilet_1", "v_lavabo_1", "v_faucet_3"],
    hotspots: [
      { id: "hs-s4-1", productId: "v_tile_6", x: 50, y: 85, label: "Sàn gạch giả gỗ siêu bền" },
      { id: "hs-s4-2", productId: "v_faucet_3", x: 80, y: 55, label: "Thiết bị inox cơ bản bền bỉ" }
    ],
    whyItWorks: ["Không lo khách phá", "Chi phí khấu hao thấp"],
    productCount: 4,
    suitableFor: ["Căn hộ dịch vụ dài hạn"],
    painPoints: ["Khách thuê làm hỏng sàn gỗ, ngấm nước tủ"],
    keyProducts: ["Sàn gạch/nhựa hèm khoá", "Sứ vệ sinh cơ bản dễ thay"],
    estimatedBudgetMin: 30000000,
    estimatedBudgetMax: 50000000,
    sourceNote: "Sử dụng dữ liệu catalogue tham khảo"
  },
  {
    id: "vc-stu-5",
    slug: "rental-makeover-ngan-sach-thap",
    title: "Rental makeover ngân sách thấp",
    roomType: "Homestay",
    style: "Budget",
    budgetRange: "Dưới 20 triệu",
    areaSize: "15-20m²",
    shortDescription: "Concept demo",
    description: "Biến hoá phòng cũ thành góc xinh chỉ với sơn và dán.",
    longDescription: "Giữ lại những món đồ cốt lõi, lột xác bằng cách sơn lại tường, dán decal giả đá cho mặt bếp và thêm thảm trải sàn giả vân gỗ.",
    image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1080&q=80",
    imageAlt: "Cải tạo phòng thuê ngân sách thấp",
    productIds: ["v_acc_2", "v_mirror_1"],
    hotspots: [
      { id: "hs-s5-1", productId: "v_mirror_1", x: 40, y: 30, label: "Gương dán tường" },
      { id: "hs-s5-2", productId: "v_acc_2", x: 60, y: 50, label: "Kệ để đồ lắp ghép" }
    ],
    whyItWorks: ["Cực rẻ", "Tự làm được (DIY)", "Hiệu quả thị giác cao"],
    productCount: 2,
    suitableFor: ["Sinh viên đi thuê", "Cải tạo mặt bằng giá rẻ"],
    painPoints: ["Không có tiền đập phá làm mới"],
    keyProducts: ["Sơn tường nhạt", "Decal, sàn nhựa bóc dán"],
    estimatedBudgetMin: 5000000,
    estimatedBudgetMax: 12000000,
    sourceNote: "Sử dụng dữ liệu catalogue tham khảo"
  }
];
