/**
 * Serializable Room Studio state and the pure operations over it.
 *
 * Everything here is plain data — no Three.js objects, no React, no DOM — so the
 * whole studio can be saved, restored, and later synced to Supabase by writing
 * this one object.
 */

import { DEFAULT_DIMENSIONS, clampDimensions, type RoomDimensions } from './roomGeometry';
import {
  DEFAULT_SURFACE_STYLES,
  LEGACY_MATERIAL_STYLES,
  normalizeSurfaceStyle,
  type SurfaceId,
  type SurfaceStyle,
} from './materials';
import { clampToRoom, getDefaultPlacement, type PlacementType, type Vec3, type WallId } from './placementRules';
import { getRealWorldSize } from './assetResolver';
import type { RoomStudioProduct } from './productAdapter';
import type { UtilityPoint } from '@/lib/technical-advisor/types';

export const ROOM_STATE_VERSION = 1;

export interface PlacedProduct {
  instanceId: string;
  productId: string;
  position: Vec3;
  /** Yaw in radians. Products only ever rotate about the vertical axis — a
   *  consumer never needs pitch/roll, and exposing them would feel like CAD. */
  rotationY: number;
  /** Uniform multiplier on top of real-world normalisation. Reserved; the UI
   *  does not let customers distort products away from true scale. */
  scale?: number;
  placementType: PlacementType;
  wall?: WallId;
}

export interface RoomState {
  version: number;
  dimensions: RoomDimensions;
  /**
   * Structured finish per surface — material, colour and finish are three
   * separate decisions, never one mixed label. See ./materials.ts.
   */
  surfaceStyles: Record<SurfaceId, SurfaceStyle>;
  placedProducts: PlacedProduct[];
  /**
   * Optional photo of the customer's real room, shown as context beside the 3D
   * view. It is NEVER used to derive geometry — LivLab does not claim to
   * reconstruct dimensions from a single image.
   */
  roomContextImage?: string;
  roomContextLabel?: string;
  /**
   * What the customer says they want to spend, in VND. Optional: the studio is
   * fully usable without it, and LivLab Expert reports budget fit only when it
   * is set rather than inventing a target.
   */
  targetBudget?: number;
  /** Style tags the customer picked, reused as context for LivLab Expert. */
  stylePreferences?: string[];
  /**
   * Cấp/thoát nước points the customer has DECLARED. Optional and always
   * manual: LivLab never infers plumbing positions from a photo or a floor
   * plan, and the Technical Advisor reports "chưa có dữ liệu" rather than
   * assuming when this is empty.
   */
  utilityPoints?: UtilityPoint[];
}

export function createInitialRoomState(): RoomState {
  return {
    version: ROOM_STATE_VERSION,
    dimensions: { ...DEFAULT_DIMENSIONS },
    surfaceStyles: {
      floor: { ...DEFAULT_SURFACE_STYLES.floor },
      walls: { ...DEFAULT_SURFACE_STYLES.walls },
    },
    placedProducts: [],
  };
}

let instanceCounter = 0;

/**
 * Ids are generated by the caller, before the state update runs, so that state
 * updaters stay pure — they must be safe to call twice (React StrictMode does
 * exactly that) without minting two different ids.
 */
export function createInstanceId(productId: string): string {
  instanceCounter += 1;
  return `ri_${Date.now().toString(36)}_${instanceCounter}_${productId}`;
}

// ─── Operations (pure: always return a new state) ─────────────────────────────

export function setDimensions(state: RoomState, dimensions: RoomDimensions): RoomState {
  const next = clampDimensions(dimensions);
  return { ...state, dimensions: next };
}

/**
 * Re-clamps every placed product after the room changes size, so shrinking a
 * room can never leave products stranded inside a wall.
 */
export function reflowPlacements(
  state: RoomState,
  resolveProduct: (productId: string) => RoomStudioProduct | undefined
): RoomState {
  const placedProducts = state.placedProducts.map((placed) => {
    const product = resolveProduct(placed.productId);
    if (!product) return placed;
    const size = getRealWorldSize(product);
    const position = clampToRoom(placed.position, {
      dimensions: state.dimensions,
      size,
      placementType: placed.placementType,
      wall: placed.wall,
    });
    return { ...placed, position };
  });
  return { ...state, placedProducts };
}

/**
 * Applies a partial change to one surface's style. The patch is re-normalised,
 * so switching material while an unavailable colour/finish is selected snaps to
 * something the catalogue actually sells rather than storing a dead combination.
 */
export function setSurfaceStyle(
  state: RoomState,
  surface: SurfaceId,
  patch: Partial<SurfaceStyle>
): RoomState {
  const next = normalizeSurfaceStyle(surface, { ...state.surfaceStyles[surface], ...patch });
  return {
    ...state,
    surfaceStyles: { ...state.surfaceStyles, [surface]: next },
  };
}

export function addProduct(
  state: RoomState,
  product: RoomStudioProduct,
  options: { instanceId: string; atPoint?: Vec3 }
): RoomState {
  const size = getRealWorldSize(product);
  // Spread every new arrival along x by how many products are already in the
  // room, so nothing lands on top of anything else and looks like it failed to
  // appear — a basin stacked on a toilet reads as a bug, not as a suggestion.
  const neighbourCount = state.placedProducts.length;
  const placementCtx = {
    dimensions: state.dimensions,
    size,
    placementType: product.placementType,
  };
  const { position, rotationY, wall } = getDefaultPlacement(
    placementCtx,
    product.normalizedCategory,
    neighbourCount
  );

  // A drop point only suggests where the customer aimed; placement rules still
  // decide the constrained axes (a mirror stays on its wall, a toilet stays on
  // the floor) and clamp the result inside the room.
  const finalPosition = options.atPoint
    ? clampToRoom(options.atPoint, { ...placementCtx, wall })
    : position;

  const placed: PlacedProduct = {
    instanceId: options.instanceId,
    productId: product.id,
    position: finalPosition,
    rotationY,
    placementType: product.placementType,
    wall,
  };

  return { ...state, placedProducts: [...state.placedProducts, placed] };
}

export function removeProduct(state: RoomState, instanceId: string): RoomState {
  return { ...state, placedProducts: state.placedProducts.filter((p) => p.instanceId !== instanceId) };
}

export function updatePlacement(
  state: RoomState,
  instanceId: string,
  updates: Partial<Pick<PlacedProduct, 'position' | 'rotationY' | 'wall'>>
): RoomState {
  return {
    ...state,
    placedProducts: state.placedProducts.map((p) => (p.instanceId === instanceId ? { ...p, ...updates } : p)),
  };
}

export function duplicateProduct(state: RoomState, instanceId: string, newInstanceId: string): RoomState {
  const source = state.placedProducts.find((p) => p.instanceId === instanceId);
  if (!source) return state;
  const copy: PlacedProduct = {
    ...source,
    instanceId: newInstanceId,
    position: [source.position[0] + 0.25, source.position[1], source.position[2] + 0.1],
  };
  return { ...state, placedProducts: [...state.placedProducts, copy] };
}

export function clearProducts(state: RoomState): RoomState {
  return { ...state, placedProducts: [] };
}

export function setRoomContextImage(state: RoomState, image?: string, label?: string): RoomState {
  return { ...state, roomContextImage: image, roomContextLabel: label };
}

export function setTargetBudget(state: RoomState, targetBudget?: number): RoomState {
  const safe = targetBudget !== undefined && Number.isFinite(targetBudget) && targetBudget > 0 ? targetBudget : undefined;
  return { ...state, targetBudget: safe };
}

export function setStylePreferences(state: RoomState, stylePreferences: string[]): RoomState {
  return { ...state, stylePreferences };
}

export function addUtilityPoint(state: RoomState, point: UtilityPoint): RoomState {
  return { ...state, utilityPoints: [...(state.utilityPoints ?? []), point] };
}

export function removeUtilityPoint(state: RoomState, id: string): RoomState {
  return { ...state, utilityPoints: (state.utilityPoints ?? []).filter((p) => p.id !== id) };
}

// ─── Serialization ────────────────────────────────────────────────────────────

/**
 * Reads one surface's finish from a snapshot. Handles three shapes: the current
 * structured style, a pre-refactor mixed material id (`"tile-beige"`), and
 * nothing at all. Every result is normalised, so a snapshot naming a material
 * that is no longer offered on that surface still renders.
 */
function parseSurfaceStyle(
  surface: SurfaceId,
  style: unknown,
  legacyMaterialId: unknown
): SurfaceStyle {
  if (style && typeof style === 'object') {
    return normalizeSurfaceStyle(surface, style as Partial<SurfaceStyle>);
  }
  if (typeof legacyMaterialId === 'string' && LEGACY_MATERIAL_STYLES[legacyMaterialId]) {
    return normalizeSurfaceStyle(surface, LEGACY_MATERIAL_STYLES[legacyMaterialId]);
  }
  return { ...DEFAULT_SURFACE_STYLES[surface] };
}

/**
 * Accepts anything (an old snapshot, a Supabase row, junk) and returns a state
 * that is safe to render. Unknown or corrupt fields fall back to defaults rather
 * than throwing — a bad cached value must never break the studio.
 */
export function deserializeRoomState(raw: unknown): RoomState {
  const base = createInitialRoomState();
  if (!raw || typeof raw !== 'object') return base;
  // `selectedMaterials` is the pre-refactor field; it is not on RoomState any
  // more, so it is read off the untyped snapshot.
  const data = raw as Partial<RoomState> & { selectedMaterials?: Record<string, unknown> };

  const dimensions = clampDimensions(data.dimensions ?? base.dimensions);

  const placedProducts = Array.isArray(data.placedProducts)
    ? data.placedProducts
        .filter((p): p is PlacedProduct =>
          Boolean(
            p &&
              typeof p.instanceId === 'string' &&
              typeof p.productId === 'string' &&
              Array.isArray(p.position) &&
              p.position.length === 3 &&
              p.position.every((n) => typeof n === 'number' && Number.isFinite(n))
          )
        )
        .map((p) => ({
          instanceId: p.instanceId,
          productId: p.productId,
          position: [p.position[0], p.position[1], p.position[2]] as Vec3,
          rotationY: Number.isFinite(p.rotationY) ? p.rotationY : 0,
          scale: Number.isFinite(p.scale as number) ? p.scale : undefined,
          placementType: (p.placementType ?? 'floor') as PlacementType,
          wall: p.wall,
        }))
    : [];

  return {
    version: ROOM_STATE_VERSION,
    dimensions,
    surfaceStyles: {
      floor: parseSurfaceStyle('floor', data.surfaceStyles?.floor, data.selectedMaterials?.floor),
      walls: parseSurfaceStyle('walls', data.surfaceStyles?.walls, data.selectedMaterials?.walls),
    },
    placedProducts,
    roomContextImage: typeof data.roomContextImage === 'string' ? data.roomContextImage : undefined,
    roomContextLabel: typeof data.roomContextLabel === 'string' ? data.roomContextLabel : undefined,
    targetBudget:
      typeof data.targetBudget === 'number' && Number.isFinite(data.targetBudget) && data.targetBudget > 0
        ? data.targetBudget
        : undefined,
    stylePreferences: Array.isArray(data.stylePreferences)
      ? data.stylePreferences.filter((s): s is string => typeof s === 'string')
      : undefined,
    // Older snapshots predate utility points; absence simply means "not
    // declared", which every technical rule already handles.
    utilityPoints: Array.isArray(data.utilityPoints)
      ? data.utilityPoints.filter(
          (p): p is UtilityPoint =>
            Boolean(p) &&
            typeof p.id === 'string' &&
            typeof p.type === 'string' &&
            Array.isArray(p.position) &&
            p.position.length === 3 &&
            p.position.every((n) => typeof n === 'number' && Number.isFinite(n))
        )
      : undefined,
  };
}

export function serializeRoomState(state: RoomState): RoomState {
  // `blob:` URLs from a local file upload die with the page, so persisting one
  // would restore a broken image. Drop it and keep the rest of the room.
  const image = state.roomContextImage?.startsWith('blob:') ? undefined : state.roomContextImage;
  return { ...state, version: ROOM_STATE_VERSION, roomContextImage: image };
}
