/**
 * Serializable Room Studio state and the pure operations over it.
 *
 * Everything here is plain data — no Three.js objects, no React, no DOM — so the
 * whole studio can be saved, restored, and later synced to Supabase by writing
 * this one object.
 */

import { DEFAULT_DIMENSIONS, clampDimensions, type RoomDimensions } from './roomGeometry';
import { DEFAULT_FLOOR_MATERIAL_ID, DEFAULT_WALL_MATERIAL_ID, type SurfaceId } from './materials';
import { clampToRoom, getDefaultPlacement, type PlacementType, type Vec3, type WallId } from './placementRules';
import { getRealWorldSize } from './assetResolver';
import type { RoomStudioProduct } from './productAdapter';

export const ROOM_STATE_VERSION = 1;

export interface PlacedProduct {
  instanceId: string;
  productId: string;
  position: Vec3;
  /** Yaw in radians. Products only ever rotate about the vertical axis — a
   *  consumer never needs pitch/roll, and exposing them would feel like CAD. */
  rotationY: number;
  /** Uniform multiplier on top of real-world normalisation. Reserved; the UI
   *  does not let customers distort products away from true scale. */
  scale?: number;
  placementType: PlacementType;
  wall?: WallId;
}

export interface RoomState {
  version: number;
  dimensions: RoomDimensions;
  selectedMaterials: Record<SurfaceId, string>;
  placedProducts: PlacedProduct[];
  /**
   * Optional photo of the customer's real room, shown as context beside the 3D
   * view. It is NEVER used to derive geometry — LivLab does not claim to
   * reconstruct dimensions from a single image.
   */
  roomContextImage?: string;
  roomContextLabel?: string;
}

export function createInitialRoomState(): RoomState {
  return {
    version: ROOM_STATE_VERSION,
    dimensions: { ...DEFAULT_DIMENSIONS },
    selectedMaterials: {
      floor: DEFAULT_FLOOR_MATERIAL_ID,
      walls: DEFAULT_WALL_MATERIAL_ID,
    },
    placedProducts: [],
  };
}

let instanceCounter = 0;

/**
 * Ids are generated by the caller, before the state update runs, so that state
 * updaters stay pure — they must be safe to call twice (React StrictMode does
 * exactly that) without minting two different ids.
 */
export function createInstanceId(productId: string): string {
  instanceCounter += 1;
  return `ri_${Date.now().toString(36)}_${instanceCounter}_${productId}`;
}

// ─── Operations (pure: always return a new state) ─────────────────────────────

export function setDimensions(state: RoomState, dimensions: RoomDimensions): RoomState {
  const next = clampDimensions(dimensions);
  return { ...state, dimensions: next };
}

/**
 * Re-clamps every placed product after the room changes size, so shrinking a
 * room can never leave products stranded inside a wall.
 */
export function reflowPlacements(
  state: RoomState,
  resolveProduct: (productId: string) => RoomStudioProduct | undefined
): RoomState {
  const placedProducts = state.placedProducts.map((placed) => {
    const product = resolveProduct(placed.productId);
    if (!product) return placed;
    const size = getRealWorldSize(product);
    const position = clampToRoom(placed.position, {
      dimensions: state.dimensions,
      size,
      placementType: placed.placementType,
      wall: placed.wall,
    });
    return { ...placed, position };
  });
  return { ...state, placedProducts };
}

export function setMaterial(state: RoomState, surface: SurfaceId, materialId: string): RoomState {
  return {
    ...state,
    selectedMaterials: { ...state.selectedMaterials, [surface]: materialId },
  };
}

export function addProduct(
  state: RoomState,
  product: RoomStudioProduct,
  options: { instanceId: string; atPoint?: Vec3 }
): RoomState {
  const size = getRealWorldSize(product);
  // Spread every new arrival along x by how many products are already in the
  // room, so nothing lands on top of anything else and looks like it failed to
  // appear — a basin stacked on a toilet reads as a bug, not as a suggestion.
  const neighbourCount = state.placedProducts.length;
  const placementCtx = {
    dimensions: state.dimensions,
    size,
    placementType: product.placementType,
  };
  const { position, rotationY, wall } = getDefaultPlacement(
    placementCtx,
    product.normalizedCategory,
    neighbourCount
  );

  // A drop point only suggests where the customer aimed; placement rules still
  // decide the constrained axes (a mirror stays on its wall, a toilet stays on
  // the floor) and clamp the result inside the room.
  const finalPosition = options.atPoint
    ? clampToRoom(options.atPoint, { ...placementCtx, wall })
    : position;

  const placed: PlacedProduct = {
    instanceId: options.instanceId,
    productId: product.id,
    position: finalPosition,
    rotationY,
    placementType: product.placementType,
    wall,
  };

  return { ...state, placedProducts: [...state.placedProducts, placed] };
}

export function removeProduct(state: RoomState, instanceId: string): RoomState {
  return { ...state, placedProducts: state.placedProducts.filter((p) => p.instanceId !== instanceId) };
}

export function updatePlacement(
  state: RoomState,
  instanceId: string,
  updates: Partial<Pick<PlacedProduct, 'position' | 'rotationY' | 'wall'>>
): RoomState {
  return {
    ...state,
    placedProducts: state.placedProducts.map((p) => (p.instanceId === instanceId ? { ...p, ...updates } : p)),
  };
}

export function duplicateProduct(state: RoomState, instanceId: string, newInstanceId: string): RoomState {
  const source = state.placedProducts.find((p) => p.instanceId === instanceId);
  if (!source) return state;
  const copy: PlacedProduct = {
    ...source,
    instanceId: newInstanceId,
    position: [source.position[0] + 0.25, source.position[1], source.position[2] + 0.1],
  };
  return { ...state, placedProducts: [...state.placedProducts, copy] };
}

export function clearProducts(state: RoomState): RoomState {
  return { ...state, placedProducts: [] };
}

export function setRoomContextImage(state: RoomState, image?: string, label?: string): RoomState {
  return { ...state, roomContextImage: image, roomContextLabel: label };
}

// ─── Serialization ────────────────────────────────────────────────────────────

/**
 * Accepts anything (an old snapshot, a Supabase row, junk) and returns a state
 * that is safe to render. Unknown or corrupt fields fall back to defaults rather
 * than throwing — a bad cached value must never break the studio.
 */
export function deserializeRoomState(raw: unknown): RoomState {
  const base = createInitialRoomState();
  if (!raw || typeof raw !== 'object') return base;
  const data = raw as Partial<RoomState>;

  const dimensions = clampDimensions(data.dimensions ?? base.dimensions);

  const placedProducts = Array.isArray(data.placedProducts)
    ? data.placedProducts
        .filter((p): p is PlacedProduct =>
          Boolean(
            p &&
              typeof p.instanceId === 'string' &&
              typeof p.productId === 'string' &&
              Array.isArray(p.position) &&
              p.position.length === 3 &&
              p.position.every((n) => typeof n === 'number' && Number.isFinite(n))
          )
        )
        .map((p) => ({
          instanceId: p.instanceId,
          productId: p.productId,
          position: [p.position[0], p.position[1], p.position[2]] as Vec3,
          rotationY: Number.isFinite(p.rotationY) ? p.rotationY : 0,
          scale: Number.isFinite(p.scale as number) ? p.scale : undefined,
          placementType: (p.placementType ?? 'floor') as PlacementType,
          wall: p.wall,
        }))
    : [];

  return {
    version: ROOM_STATE_VERSION,
    dimensions,
    selectedMaterials: {
      floor: data.selectedMaterials?.floor ?? base.selectedMaterials.floor,
      walls: data.selectedMaterials?.walls ?? base.selectedMaterials.walls,
    },
    placedProducts,
    roomContextImage: typeof data.roomContextImage === 'string' ? data.roomContextImage : undefined,
    roomContextLabel: typeof data.roomContextLabel === 'string' ? data.roomContextLabel : undefined,
  };
}

export function serializeRoomState(state: RoomState): RoomState {
  // `blob:` URLs from a local file upload die with the page, so persisting one
  // would restore a broken image. Drop it and keep the rest of the room.
  const image = state.roomContextImage?.startsWith('blob:') ? undefined : state.roomContextImage;
  return { ...state, version: ROOM_STATE_VERSION, roomContextImage: image };
}
